'use strict';

const fs = require('fs');
const path = require('path');
const ponytailPolicy = require('../../lib/ponytail-policy.cjs');
const assuranceContext = require('../../lib/runtime-assurance-context.cjs');
const agentRouting = require('../../lib/agent-routing.cjs');
const changeImpact = require('../../lib/change-impact.cjs');

const fingerprint = 'a'.repeat(64);
const now = '2026-08-16T12:00:00.000Z';
const lenses = ['correctness_regression', 'edge_security_data', 'requirements_evidence'];
const binding = {
  work_id: 'quality-tooling', source_revision: 'f10-quality-tooling',
  sealed_revision: 9, implementation_fingerprint: fingerprint,
  acceptance_manifest_id: 'AC-QUALITY', acceptance_manifest_version: 1
};
const manifest = {
  schema: 'AcceptanceManifest/v1', id: binding.acceptance_manifest_id, version: 1,
  ac_ids: ['AC-QUALITY-1'], source: 'WORK.md', scope: 'agent-runtime/**',
  source_revision: binding.source_revision,
  contracts: [{ id: 'AC-QUALITY-1', definition: 'quality checks run', sr: 'SR-QUALITY-1', evidence: ['Static'] }]
};
function ponytailDecision(overrides = {}) {
  const value = {
    schema: 'PonytailPolicyDecision/v1', work_id: overrides.work_id || binding.work_id, source_revision: overrides.source_revision || binding.source_revision,
    role: 'executor', phase: 'execute', mode: 'full', stack_release: 'gsd-1.11.0_ponytail-4.9.0', gsd_version: '1.11.0', ponytail_version: '4.9.0',
    skill_path: 'surface/.codex/skills/ponytail/SKILL.md', skill_sha256: '1316a2f3f95741d2300b116fe0c2d81ce4a9568656ed0a62643f54aaf09957f2', capability_epoch: 'host-1',
    degraded: false, cache_hit: false, mutation_allowed: true, evidence_pointer: '.planning/agent-flow/test-output/ponytail-policy/test.json', reason: 'trusted managed Ponytail stack verified',
    policy_fragment: 'Apply Ponytail only to implementation mechanics.', next_action: 'Attach the compact policy fragment only to the permitted code-oriented dispatch.'
  };
  return { ...value, decision_digest: ponytailPolicy.decisionDigest(value) };
}
function changeImpactFixture(phase = 'pre') {
  const value = {
    schema: 'ChangeImpactAssessment/v1', assessment_id: `impact-quality-${phase}`, work_id: binding.work_id, cycle_id: 'cycle-quality', source_revision: binding.source_revision, scope_id: 'scope-quality', phase,
    snapshot_id: null, implementation_fingerprint: phase === 'post' ? fingerprint : null, predicted_paths: ['agent-runtime/lib/runtime.cjs'], direct_impacts: ['runtime gate'], transitive_impacts: [], contract_impacts: [], behavioral_impacts: [], security_impacts: [], verified_paths: phase === 'post' ? ['agent-runtime/lib/runtime.cjs'] : [], unverified_edges: [], unknown_edges: [], unexpected_paths: [], risk_flags: [], predicted_test_profile: 'focused', status: 'pass', evidence_pointers: ['WORK.md#impact'], assessed_by: 'runtime:test', created_at: now
  };
  return { ...value, digest: changeImpact.digest(value) };
}
const deployment = {
  schema: 'DeploymentManifest/v1', ...binding, delivery_cycle_id: 'cycle-1',
  created: [], modified: ['agent-runtime/lib/runtime.cjs'], deploy: [],
  do_not_deploy: ['agent-runtime/lib/runtime.cjs'],
  post_deployment_checks: [{ id: 'check-quality', step: 'Run the quality gate.', expected: 'All checks pass.', ac_refs: ['AC-QUALITY-1'] }]
};
const projectRegistry = {
  schemaVersion: 'project-registry.v1', portfolio_port: 6420,
  tenants: [{ tenant_id: 'sample-tenant', title: 'SAMPLE-TENANT', wiki_root: 'docs/tenants/sample-tenant/wiki', wiki_output_root: '.planning/agent-flow/wiki-output/sample-tenant/_tenant', internal_root: 'docs/tenants/sample-tenant', ledger_root: 'backlogs/tenants/sample-tenant/backlog', task_prefix: 'SAMPLE-TENANT', dashboard_port: 6501, code_selectors: ['src/project/**'], delivery_group: 'sample-tenant' }],
  projects: [{ project_id: 'sample-project', title: 'Sample Project', tenant_id: 'sample-tenant', wiki_root: 'docs/tenants/sample-tenant/wiki/Projects/Sample Project', wiki_path: 'docs/tenants/sample-tenant/wiki/Projects/Sample Project.md', wiki_output_root: '.planning/agent-flow/wiki-output/sample-tenant/sample-project', internal_root: 'docs/tenants/sample-tenant/internal/projects/sample-project', ledger_root: 'backlogs/tenants/sample-tenant/projects/sample-project/backlog', task_prefix: 'SAMPLE-TENANT-SAMPLE-PROJECT', dashboard_port: 6502, code_selectors: ['src/project/**'], delivery_group: 'sample-tenant-sample-project' }]
};
function deploymentManifest(c, changed = 'agent-runtime/lib/runtime.cjs') {
  return { schema: 'DeploymentManifest/v1', work_id: c.work_id, source_revision: c.source_revision, sealed_revision: c.sealed_revision, implementation_fingerprint: c.implementation_fingerprint, acceptance_manifest_id: c.acceptance_manifest.id, acceptance_manifest_version: c.acceptance_manifest.version, delivery_cycle_id: c.delivery_cycle_id, created: [], modified: [changed], deploy: [], do_not_deploy: [changed], post_deployment_checks: [{ id: 'check-current', step: 'Run the current acceptance check.', expected: 'The current acceptance check passes.', ac_refs: [c.acceptance_manifest.ac_ids[0]] }] };
}
/** @param {Record<string, any>} overrides @returns {any} */
function checkpoint(overrides = {}) {
  return {
    schema: 'WorkCheckpoint/v2', work_id: binding.work_id, revision: 9,
    lifecycle_state: 'VERIFY', protocol_version: 'agent-development-runtime/v2', route: 'R3',
    risk: 'medium', change_kind: 'feature', source_revision: binding.source_revision,
    allowed_paths: ['agent-runtime/lib/runtime.cjs'], fingerprint_paths: ['agent-runtime/lib/runtime.cjs'],
    source_plan: { br: 'quality', sr: 'quality checks', ac: 'tests pass', gaps: ['GAP-NONE'], scope: 'runtime', verification: 'tests', rollback_cleanup: 'revert tooling' },
    acceptance: ['AC-QUALITY-1'], test_plan: ['npm test'], acceptance_manifest: manifest,
    reviews: [], verification: [], evidence: [], recovery_evidence: [], leases: [], imports: [],
    review_generation: 0, review_generation_ledger: [], review_dispatch_reservation_ledger: [], question_candidates: [], change_impact_required: false,
    correction_count: 0, review_failure_count: 0, review_failure_streak: 0, architect_diagnosis_count: 0, architect_dispatch_ledger: [], architect_dispatch_disqualification_history: [], architecture_diagnosis_history: [], next_action: 'verify',
    sealed_revision: binding.sealed_revision, sealed_at: now, implementation_fingerprint: binding.implementation_fingerprint,
    implementation_policy: ponytailDecision(overrides),
    ...overrides
  };
}
function fixtures() {
  const agentRegistry = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../../config/agent-profiles.v1.json'), 'utf8'));
  const agentRoutingDecision = agentRouting.resolve({ role: 'researcher', phase: 'trace', work_id: binding.work_id, task_id: 'research-quality', scope_id: 'scope-quality', source_revision: binding.source_revision }, { registry: agentRegistry });
  const agentTaskContract = agentRouting.contract({ registry: agentRegistry, allowed_paths: ['docs/project'], protected_paths: ['.agent'], stop_condition: 'Return a compact research result.' }, agentRoutingDecision);
  const packet = { schema: 'BlindReviewPacket/v2', packet_id: 'packet-quality', packet_version: 1, wave: 1, generation: 1, status: 'frozen', ...binding, required_profile: { model: 'configured', reasoning: 'high' }, review_scope: { paths: ['agent-runtime/lib/runtime.cjs'], absence_assertions: {} }, profile_attestation_set: 'dispatch.json' };
  const context = assuranceContext.build({ ...binding, revision: 9, lifecycle_state: 'VERIFY', packet, review_mode: 'exact-three', requested_reviewers: 3, capability_epoch: 'host-1', lease_expires_at: '2099-08-16T12:00:00.000Z', next_action: 'Dispatch exactly three independent blind reviewers.' });
  const delta = assuranceContext.statusDelta(context, assuranceContext.build({ ...binding, revision: 10, lifecycle_state: 'VERIFY', packet, review_mode: 'exact-three', requested_reviewers: 3, capability_epoch: 'host-1', lease_expires_at: '2099-08-16T12:00:00.000Z', next_action: 'Record the next receipt.' }));
  const reviewHash = 'b'.repeat(64);
  const reviewPreflight = {
    schema: 'ReviewPreflight/v1', status: 'pass', operation_id: 'preflight-quality', work_id: binding.work_id,
    source_revision: binding.source_revision, sealed_revision: binding.sealed_revision, implementation_fingerprint: binding.implementation_fingerprint,
    packet_id: packet.packet_id, packet_version: packet.packet_version, wave: packet.wave, generation: packet.generation,
    review_mode: 'exact-three', requested_reviewers: 3, dirty_overlap: [], source_hashes: [{ path: 'agent-runtime/lib/runtime.cjs', sha256: reviewHash }],
    document_hashes: [{ path: 'agent-runtime/TESTING.md', sha256: reviewHash }], profile: { model: 'configured', reasoning: 'high', attestable: true },
    lease: { status: 'active', expires_at: '2099-08-16T12:00:00.000Z' }, capability_epoch: 'host-1', active_dispatch: false, previous_packet_id: null,
    snapshot: { source_revision: binding.source_revision, sealed_revision: binding.sealed_revision, implementation_fingerprint: binding.implementation_fingerprint,
      packet_id: packet.packet_id, packet_version: packet.packet_version, wave: packet.wave, generation: packet.generation,
      source_hashes: [{ path: 'agent-runtime/lib/runtime.cjs', sha256: reviewHash }], document_hashes: [{ path: 'agent-runtime/TESTING.md', sha256: reviewHash }],
      profile: { model: 'configured', reasoning: 'high' }, capability_epoch: 'host-1', lease_expires_at: '2099-08-16T12:00:00.000Z' },
    created_at: now, next_action: 'Dispatch exactly three independent blind reviewers.'
  };
  const reviewBatch = {
    schema: 'ReviewBatch/v1', status: 'running', batch_id: 'review-batch-quality', operation_id: 'preflight-quality', work_id: binding.work_id,
    packet_id: packet.packet_id, fingerprint: binding.implementation_fingerprint, review_mode: 'exact-three', requested: 3, started: 3, completed: 0, cancelled: 0,
    entries: lenses.map((lens, index) => ({ handle_id: `handle-${index}`, task_id: `t${index}`, dispatch_id: `d${index}`, reviewer_id: `r${index}`, lens, host_handle: `host-${index}` })),
    preflight_id: 'preflight-quality', created_at: now, next_action: 'Wait for the review batch summary.'
  };
  const projectContext = { schema: 'ProjectContext/v1', tenant_id: 'sample-tenant', primary_project_id: 'sample-project', affected_project_ids: ['sample-project'], ledger_id: 'project:sample-tenant/sample-project', task_id: 'SAMPLE-TENANT-SAMPLE-PROJECT-1', wiki_roots: ['docs/tenants/sample-tenant/wiki', 'docs/tenants/sample-tenant/wiki/Projects/Sample Project'], provider_revision: 'provider-r1' };
  return {
    'ponytail-policy-decision.v1.schema.json': ponytailDecision(),
    'review-preflight.v1.schema.json': reviewPreflight,
    'review-batch.v1.schema.json': reviewBatch,
    'verify-bundle.v1.schema.json': { schema: 'VerifyBundle/v1', artifact_dir: '.planning/agent-flow/test-output/operator', checks: [{ id: 'syntax', command: 'node', args: ['--check', 'file.cjs'], cwd: '.' }] },
    'architect-diagnostic-dispatch.v1.schema.json': { schema: 'ArchitectDiagnosticDispatch/v1', ...binding, dispatch_id: 'architect-dispatch-1', task_id: 'architect-task-1', handle_id: 'architect-handle-1', architect_id: 'architect-1', requested_model: 'gpt-5.6-sol', requested_reasoning_effort: 'high', history_isolation: true, requirement_pointers: ['BR:quality', 'SR:quality', 'AC:AC-QUALITY-1'], external_observation_pointers: ['observation:quality-failure'], forbidden_context_asserted: true, reserved_at: now },
    'architect-dispatch-disqualification.v1.schema.json': { schema: 'ArchitectDispatchDisqualification/v1', ...binding, disqualification_id: 'architect-disqualification-1', dispatch_id: 'architect-dispatch-1', task_id: 'architect-task-1', handle_id: 'architect-handle-1', architect_id: 'architect-1', reason: 'history_isolation_failed', evidence_pointer: 'current-thread#architect-isolation-failure', disqualified_by: 'root', timestamp: now },
    'architecture-diagnosis.v1.schema.json': { schema: 'ArchitectureDiagnosis/v1', ...binding, diagnosis_id: 'architecture-diagnosis-1', dispatch_id: 'architect-dispatch-1', task_id: 'architect-task-1', handle_id: 'architect-handle-1', architect_id: 'architect-1', history_isolation: true, blind_context_asserted: true, profile_verified: true, profile_verification: { verified_model: 'gpt-5.6-sol', verified_reasoning_effort: 'high', verification_source: 'tests/architect-profile', verification_pointer: 'tests/architect-profile', verified_at: now }, outcome: 'defect_found', affected_ac_ids: ['AC-QUALITY-1'], root_cause_hypothesis: 'The externally observable behavior conflicts with the current acceptance contract.', correction_direction: 'Realign the system behavior with the current acceptance contract.', dispatch_digest: 'b'.repeat(64), timestamp: now },
    'blind-review-packet.v2.schema.json': packet,
    'project-context.v1.schema.json': projectContext,
    'backlog-projection.v1.schema.json': { schema: 'BacklogProjection/v1', ledger_id: projectContext.ledger_id, task_id: projectContext.task_id, desired_status: 'In Development', observed_status: 'In Development', provider_revision: projectContext.provider_revision, sync_status: 'synced', gap_pointer: null, error: null, updated_at: now },
    'user-testing-receipt.v1.schema.json': { schema: 'UserTestingReceipt/v1', ...binding, delivery_cycle_id: 'cycle-1', decision: 'accepted', actor: 'user', source: 'current-thread', timestamp: now, sanitized_pointers: ['current-thread#acceptance'] },
    'delivery-feedback-analysis.v1.schema.json': { schema: 'DeliveryFeedbackAnalysis/v1', analysis_id: 'analysis-quality', work_id: binding.work_id, source_revision: binding.source_revision, delivery_cycle_id: 'cycle-1', source_receipt_id: 'testing-quality', origin: 'testing', status: 'accepted', decision: 'rework', summary: 'The current testing result requires a bounded correction.', affected_ac_ids: ['AC-QUALITY-1'], affected_files: ['agent-runtime/lib/runtime.cjs'], evidence_pointers: ['current-thread#feedback'], proposed_correction: 'Apply the smallest correction and rerun the affected acceptance checks.', analyzed_by: 'quality-analyzer', analyzed_at: now, scope: 'local' },
    'correction-authorization.v1.schema.json': { schema: 'CorrectionAuthorization/v1', authorization_id: 'correction-auth-quality', work_id: binding.work_id, source_revision: binding.source_revision, delivery_cycle_id: 'cycle-1', origin: 'testing', source_receipt_id: 'testing-quality', feedback_analysis_id: 'analysis-quality', decision: 'rework', scope: 'local', affected_ac_ids: ['AC-QUALITY-1'], affected_files: ['agent-runtime/lib/runtime.cjs'], platform_knowledge_context_id: 'knowledge-quality', platform_knowledge_digest: '2'.repeat(64), disposition: 'feedback_bounded_correction', actor: 'quality-analyzer', pointer: 'WORK.md#feedback-authorization', created_at: now },
    'cross-scope-correction-authorization.v1.schema.json': { schema: 'CrossScopeCorrectionAuthorization/v1', authorization_id: 'cross-scope-auth-quality', work_id: binding.work_id, source_revision: binding.source_revision, delivery_cycle_id: 'cycle-1', origin: 'testing', source_receipt_id: 'testing-quality', feedback_analysis_id: 'analysis-quality', decision: 'rework', scope: 'cross_scope', affected_ac_ids: ['AC-QUALITY-1'], affected_files: ['agent-runtime/lib/runtime.cjs', 'agent-runtime/TESTING.md'], prior_scope_id: 'scope-quality-prior', scope_id: 'scope-quality-next', scope_contract_digest: '3'.repeat(64), platform_knowledge_context_id: 'knowledge-quality-next', platform_knowledge_digest: '4'.repeat(64), disposition: 'scope_expansion_correction', reason: 'Authorize the bounded cross-scope correction.', actor: 'quality-analyzer', pointer: 'WORK.md#cross-scope-authorization', from_revision: 9, to_revision: 10, created_at: now },
    'acceptance-manifest-repair.v1.schema.json': { schema: 'AcceptanceManifestRepair/v1', work_id: binding.work_id, source_revision: binding.source_revision, manifest, reason: 'Restore the missing typed acceptance contract definitions.', pointer: 'WORK.md#acceptance-contracts', actor: 'runtime-repair', timestamp: now },
    'coordination-scope.v1.schema.json': { schema: 'CoordinationScope/v1', work_id: 'coord-work', thread_id: 'thread-1', source_revision: binding.source_revision, contour_keys: ['br:BR-QUALITY-1', 'sr:SR-QUALITY-1', 'file:agent-runtime/lib/runtime.cjs'], exclusive_resources: ['file:agent-runtime/lib/runtime.cjs'] },
    'coordination-scope-rebind.v1.schema.json': { schema: 'CoordinationScopeRebind/v1', rebind_id: 'rebind-1', work_id: 'coord-work', previous_ticket_id: 'ticket-old', ticket_id: 'ticket-1', thread_id: 'thread-1', source_revision: binding.source_revision, resources: ['file:agent-runtime/lib/runtime.cjs'], retired_claim_ids: ['claim-old'], reason: 'Recover the stale coordination binding.', decided_by: 'runtime:test', decision_pointer: 'WORK.md#coordination-rebind', from_ledger_revision: 4, to_ledger_revision: 5, created_at: now },
    'workstream-claim.v1.schema.json': { schema: 'WorkstreamClaim/v1', claim_id: 'claim-1', ticket_id: 'ticket-1', work_id: 'coord-work', thread_id: 'thread-1', generation: 1, resources: ['file:agent-runtime/lib/runtime.cjs'], lease_expires_at: now, status: 'active', created_at: now, renewed_at: now },
    'conflict-notice.v1.schema.json': { schema: 'ConflictNotice/v1', notice_id: 'notice-1', generation: 1, contender_ticket_id: 'ticket-2', contender_work_id: 'other-work', owner_ticket_id: 'ticket-1', owner_work_id: 'coord-work', owner_thread_id: 'thread-1', resources: ['file:agent-runtime/lib/runtime.cjs'], status: 'open', acknowledgements: [], created_at: now },
    'conflict-disposition.v1.schema.json': { schema: 'ConflictDisposition/v1', disposition_id: 'disposition-1', notice_id: 'notice-1', kind: 'serialize', decided_by: 'root', decision_pointer: 'WORK.md#coordination', created_at: now },
    'release-batch.v1.schema.json': { schema: 'ReleaseBatch/v1', batch_id: 'batch-1', contour_id: 'contour-1', generation: 1, work_ids: ['coord-work'], operations: [{ order: 1, source: 'agent-runtime/lib/runtime.cjs', destination: 'runtime bundle', operation: 'copy' }], do_not_deploy: ['tests/agent-runtime/runtime-contract.test.cjs'], post_deployment_checks: [], status: 'ready_for_user_testing', created_at: now },
    'workstream-ownership-ledger.v1.schema.json': { schema: 'WorkstreamOwnershipLedger/v1', revision: 1, open_generation: 1, next_sequence: 1, tickets: [], claims: [], notices: [], dispositions: [], contours: [], batches: [], rebinds: [] },
    'architect-decision.v1.schema.json': { schema: 'ArchitectDecision/v1', decision_id: 'architect-quality', ...binding, review_generation: 1, packet_id: packet.packet_id, packet_version: 1, wave: 1, trigger_receipt_ids: ['review-quality'], trigger_finding_ids: ['finding-quality'], scope: 'cross_scope', architect_id: 'architect', profile_verified: true, architect_profile: { model: 'configured', reasoning: 'high', verification_source: 'test/architect-verifier', verification_pointer: 'tests/architect-profile', verified_at: now }, implementer_id: 'executor', decision: 'Apply the bounded correction.', decision_pointer: 'WORK.md#architect-decision', correction_pointer: 'WORK.md#architect-correction', timestamp: now, architect_not_reviewer_or_implementer: true },
    'delivery-receipt.v2.schema.json': { schema: 'DeliveryReceipt/v2', ...binding, delivery_cycle_id: 'cycle-1', decision: 'approved', actor: 'user', source: 'chat', timestamp: now, sanitized_pointers: ['WORK.md#approval'], deployment_manifest: deployment },
    'deployment-manifest.v1.schema.json': deployment,
    'dispatch-profile-attestation-set.v1.schema.json': { schema: 'DispatchProfileAttestationSet/v1', ...binding, packet_id: packet.packet_id, packet_version: 1, wave: 1, orchestrator: 'root', selector_source: 'test', requested_model: 'configured', requested_reasoning_effort: 'high', runtime_metadata_observed: false, issued_at: now, root_task_id: 'root', root_dispatch_id: 'root-d', entries: ['correctness_regression', 'edge_security_data', 'requirements_evidence'].map((lens, index) => ({ task_id: `t${index}`, dispatch_id: `d${index}`, reviewer_id: `r${index}`, lens, profile_verified: true, profile_verification: { verified_model: 'configured', verified_reasoning_effort: 'high', verification_source: 'test/profile-verifier', verification_pointer: `tests/profile-${index}`, verified_at: now } })) },
    'review-dispatch-reservation.v1.schema.json': { schema: 'ReviewDispatchReservation/v1', status: 'complete', ...binding, packet_id: packet.packet_id, packet_version: 1, wave: 1, generation: 1, requested_model: 'configured', requested_reasoning_effort: 'high', reserved_at: now, entries: ['correctness_regression', 'edge_security_data', 'requirements_evidence'].map((lens, index) => ({ handle_id: `handle-${index}`, task_id: `t${index}`, dispatch_id: `d${index}`, reviewer_id: `r${index}`, lens })) },
    'runtime-log-analysis-report.v1.schema.json': { schema: 'RuntimeLogAnalysisReport/v1', status: 'no_new_signal', analysis_window: { days: 14, from: now, to: now }, snapshot: { source_revision: binding.source_revision, runtime_version: '1.0.0', host_capability_epoch: 'host-1', snapshot_id: 'c'.repeat(64), files: [] }, source_counts: { files: 0, events: 0, recurrence_clusters: 0 }, recurrence_clusters: [], optimization_findings: [], documentation_research: [], skill_assessment: [], known_gaps: [], next_actions: ['Wait for a new runtime artifact or source snapshot.'], duration_ms: 0, watermark: { path: '.planning/agent-flow/runtime-analysis/watermark.json', snapshot_id: 'c'.repeat(64), reused: false, updated_at: now }, artifacts: [] },
    'scope-snapshot.v1.schema.json': { schema: 'ScopeSnapshot/v1', snapshot_id: 'd'.repeat(64), source_revision: binding.source_revision, implementation_fingerprint: fingerprint, scope_paths: ['agent-runtime/lib/runtime.cjs'], documentation_paths: [], files: [{ path: 'agent-runtime/lib/runtime.cjs', sha256: 'e'.repeat(64), size: 10, mode: 420, mtime_ms: 1786874400000, kind: 'implementation' }], absence_assertions: [], repository_head: null, coordination: null, captured_at: now },
    'change-impact-assessment.v1.schema.json': changeImpactFixture('pre'),
    'agent-role-profile-registry.v1.schema.json': agentRegistry,
    'agent-routing-decision.v1.schema.json': agentRoutingDecision,
    'agent-task-contract.v1.schema.json': agentTaskContract,
    'scope-integrity-report.v1.schema.json': { schema: 'ScopeIntegrityReport/v1', status: 'unchanged', gap_code: null, changed_paths: [], unchanged_paths: ['agent-runtime/lib/runtime.cjs'], old_hashes: [], new_hashes: [], owner_thread_ids: [], claim_status: [], source_revision: binding.source_revision, repository_head: null, next_action: 'Keep the current assurance set; no reviewer dispatch is needed.', evidence_pointer: 'WORK.md#scope-integrity' },
    'runtime-assurance-context.v1.schema.json': context,
    'runtime-status-delta.v1.schema.json': delta,
    'runtime-fix-notification.v1.schema.json': { schema: 'RuntimeFixNotification/v1', notification_id: 'runtime-fix-quality', created_at: now, fix_id: 'fix-quality', source_revision: binding.source_revision, severity: 'high', title: 'Runtime fix', defect: { code: 'GAP-QUALITY-001', old_behavior: 'A lawful operation was blocked.', expected_behavior: 'The lawful operation has a typed route.', fix_summary: 'Added the typed route.' }, changed_paths: ['agent-runtime/lib/runtime.cjs'], affected_work_ids: [binding.work_id], recipients: [{ work_id: binding.work_id, thread_id: 'thread-quality' }], validation: { status: 'pass', summary: 'Focused checks passed.', checks: [{ id: 'focused', status: 'pass' }] }, evidence_pointers: ['WORK.md#verification'], next_action: { operation: 'continue', summary: 'Continue with the current runtime next action.' }, delivery: { status: 'pending_host_dispatch', host_operation: 'collaboration.send_message_to_thread', gap_code: null, message_compact: 'GAP-QUALITY-001: Added the typed route. Next: Continue with the current runtime next action.' }, user_approval_required: false, authority: 'derived_non_authoritative' },
    'evidence.v1.schema.json': { schema: 'Evidence/v1', id: 'e-quality', class: 'Static', timestamp: now, ac_refs: ['AC-QUALITY-1'], pointer: 'tests/quality', ...binding },
    'import-attribution.v1.schema.json': { schema: 'ImportAttribution/v1', import_id: 'import-quality', provider: 'test', receipt_pointer: 'receipt.json', imported_at: now, status: 'accepted', ...binding },
    'legacy-import-receipt.v1.schema.json': { schema: 'LegacyImportReceipt/v1', mode: 'read_only', source_root: 'artifacts/quick-dev', records: [], inventory: { complete: true, truncated: false, visited_entries: 0, imported_files: 0, max_files: 100, max_entries: 1000, time_budget_ms: 1000, max_file_bytes: 262144, elapsed_ms: 0, bound_reason: null, gap: null }, assertions: { historical_non_authoritative: true, does_not_consume_approvals: true, does_not_consume_leases: true, ready_for_decision_is_not_human_approval: true, static_is_not_runtime: true } },
    'question-candidate.v1.schema.json': { schema: 'QuestionCandidate/v1', question_id: 'Q-QUALITY-1', work_id: binding.work_id, source_revision: binding.source_revision, targets: ['SR-QUALITY-1'], gap_class: 'conflicting', action: 'ask', type: 'resolve_conflict', criticality: 'blocking', blocking: true, decision_owner: 'user', dependencies: [], context: 'Two current authoritative sources require different observable outcomes.', evidence_pointers: ['WORK.md#conflict'], why_asked: 'The implementation branch depends on one normative outcome.', impact_if_unanswered: 'Remain blocked before mutation.', text: 'Which outcome is normative?', options: [{ id: 'A', label: 'First outcome', consequence: 'Implement the first source.', recommended: false }, { id: 'B', label: 'Second outcome', consequence: 'Implement the second source.', recommended: false }], recommendation_rationale: null, allow_other: true, allow_cannot_answer: true, status: 'open', answer: null },
    'recovery-evidence.v1.schema.json': { schema: 'RecoveryEvidence/v1', id: 'recover-quality', action: 'rollback', actor: 'tester', attribution: 'tests/quality', result: 'pass', rollback: 'revert', timestamp: now, ac_refs: ['AC-QUALITY-1'], ...binding },
    'reverse-validation-receipt.v1.schema.json': { schema: 'ReverseValidationReceipt/v1', receipt_id: 'reverse-quality', reviewer_id: 'reviewer', type: 'trace_scope', verdict: 'pass', validator: 'test', timestamp: now, evidence: ['tests/quality'], ac_refs: ['AC-QUALITY-1'], packet_id: packet.packet_id, packet_version: 1, ...binding },
    'review-receipt.v2.schema.json': { schema: 'ReviewReceipt/v2', reviewer_id: 'r0', dispatch_task_id: 't0', dispatch_id: 'd0', lens: 'correctness_regression', history_isolation: true, findings: [], verdict: 'clean', packet_id: packet.packet_id, packet_version: 1, wave: 1, ...binding },
    'runtime-receipt.v2.schema.json': { schema: 'RuntimeReceipt/v2', status: 'not_required', blocking: false, environment: 'local', actor: 'tester', timestamp: now, ac_refs: ['AC-QUALITY-1'], sanitized_pointers: [], ...binding },
    'checkpoint-protocol-migration.v1.schema.json': { schema: 'CheckpointProtocolMigration/v1', migration_id: 'quality-tooling-protocol-10', work_id: binding.work_id, from_protocol: 'agent-development-runtime/v2.2.0', to_protocol: 'agent-development-runtime/v2', from_checkpoint_schema: 'WorkCheckpoint/v2', to_checkpoint_schema: 'WorkCheckpoint/v2', from_revision: 9, to_revision: 10, source_revision: binding.source_revision, normalizations: [], reason: 'Align the legacy protocol alias with the current runtime.', pointer: 'WORK.md#protocol-upgrade', actor: 'runtime:checkpoint-upgrader', timestamp: now, status: 'applied' },
    'checkpoint-upgrade-report.v1.schema.json': { schema: 'CheckpointUpgradeReport/v1', mode: 'dry_run', root: '.', items: [{ work_id: binding.work_id, path: '.agent/work/quality-tooling/resume.json', lifecycle_state: 'VERIFY', revision: 9, status: 'already_current', from_protocol: 'agent-development-runtime/v2', to_protocol: 'agent-development-runtime/v2', normalizations: [] }], counts: { already_current: 1 } },
    'implementation-scope.v1.schema.json': { schema: 'ImplementationScope/v1', scope_id: 'scope-quality-1', work_id: binding.work_id, source_revision: binding.source_revision, ac_ids: ['AC-QUALITY-1'], allowed_paths: ['agent-runtime/lib/runtime.cjs'], changed_symbols: ['recordReviewReceipt'], non_goals: ['product source'], acceptance_trace: ['WORK.md#AC-QUALITY-1'], behavior_trace: ['SCOPE:bounded runtime receipt'], test_trace: ['tests/runtime-scope-convergence.test.cjs#scope'], diagnostic_trace: ['WORK.md#scope'], attribution: { thread_id: 'thread-quality', pointer: 'WORK.md#scope' }, owner: 'executor', created_at: now },
    'verification-scope-amendment.v1.schema.json': { schema: 'VerificationScopeAmendment/v1', amendment_id: 'verification-amendment-quality', work_id: binding.work_id, source_revision: binding.source_revision, prior_scope_id: 'scope-quality-prior', scope_id: 'scope-quality-next', ac_ids: ['AC-QUALITY-1'], added_files: ['tests/runtime-scope-convergence.test.cjs'], scope_contract_digest: 'a'.repeat(64), platform_knowledge_context_id: 'knowledge-quality-next', platform_knowledge_digest: 'b'.repeat(64), evidence: { status: 'failed', command: 'node tests/runtime-scope-convergence.test.cjs', path: 'tests/runtime-scope-convergence.test.cjs', expected: 'The focused check passes.', actual: 'The stale assertion fails.', pointer: 'WORK.md#verification-failure' }, reason: 'Authorize the bounded verification-only scope amendment.', actor: 'runtime:test', pointer: 'WORK.md#verification-amendment', from_revision: 9, to_revision: 10, timestamp: now },
    'review-set-triage.v1.schema.json': { schema: 'ReviewSetTriage/v1', triage_id: 'triage-quality-1', work_id: binding.work_id, source_revision: binding.source_revision, packet_id: packet.packet_id, generation: 1, receipt_ids: ['review-quality-1', 'review-quality-2', 'review-quality-3'], items: [{ triage_id: 'triage-item-1', receipt_id: 'review-quality-1', finding_ids: [], disposition: 'advisory', ac_refs: ['AC-QUALITY-1'], evidence_pointers: ['WORK.md#review'] }], has_blocking_current: false, status: 'accepted', owner: 'root', created_at: now },
    'checkpoint-convergence-plan.v1.schema.json': { schema: 'CheckpointConvergencePlan/v1', plan_id: 'convergence-quality-1', reason: 'Narrow the current implementation scope.', pointer: 'WORK.md#scope', actor: 'root', timestamp: now, disposition: 'narrow_current_scope', scope_contract: { schema: 'ImplementationScope/v1', scope_id: 'scope-quality-1', work_id: binding.work_id, source_revision: binding.source_revision, ac_ids: ['AC-QUALITY-1'], allowed_paths: ['agent-runtime/lib/runtime.cjs'], changed_symbols: ['recordReviewReceipt'], non_goals: ['product source'], acceptance_trace: ['WORK.md#AC-QUALITY-1'], behavior_trace: ['SCOPE:bounded runtime receipt'], test_trace: ['tests/runtime-scope-convergence.test.cjs#scope'], diagnostic_trace: ['WORK.md#scope'], attribution: { thread_id: 'thread-quality', pointer: 'WORK.md#scope' }, owner: 'executor', created_at: now } },
    'work-checkpoint.v2.schema.json': checkpoint(),
    'platform-knowledge-context-recovery.v1.schema.json': { schema: 'PlatformKnowledgeContextRecovery/v1', recovery_id: 'knowledge-recovery-quality', work_id: binding.work_id, context_id: 'knowledge-quality', cycle_id: 'cycle-quality', source_revision: binding.source_revision, scope_id: 'scope-quality', digest: 'a'.repeat(64), sealed_revision: 10, from_revision: 10, to_revision: 11, reason: 'Restore context cleared by an older runtime seal.', pointer: 'WORK.md#knowledge-recovery', actor: 'runtime:test', timestamp: now },
    'platform-knowledge-context.v1.schema.json': (() => { const base = { schema: 'PlatformKnowledgeContext/v1', context_id: 'knowledge-quality', work_id: binding.work_id, cycle_id: 'cycle-quality', source_revision: binding.source_revision, scope_id: 'scope-quality', change_kind: 'feature', br_sr_ac: { br: ['BR-QUALITY-1'], sr: ['SR-QUALITY-1'], ac: ['AC-QUALITY-1'] }, official_sources: [{ url: 'https://docs.example.test/platform/', title: 'Target Platform Academy', platform_version: '8.x', last_verified: now, source_hash: 'd'.repeat(64), applicability: 'supported UI page behavior', pointer: 'docs/project/official-academy-documentation-discovery.md' }], local_sources: [{ path: 'docs/project/official-academy-documentation-discovery.md', source_hash: 'e'.repeat(64), applicability: 'repository source priority', pointer: 'docs/project/official-academy-documentation-discovery.md' }], skills: [{ skill_id: 'target-platform-freedom-ui-frontend-diagnostics', path: '.codex/skills/target-platform-freedom-ui-frontend-diagnostics/SKILL.md', skill_sha256: 'f'.repeat(64), role: 'executor', phase: 'execute', status: 'applied', evidence_pointer: 'WORK.md#skills' }], cache: { capability_epoch: 'host-1', hit: false, snapshot_digest: '1'.repeat(64) }, warnings: [], conflicts: [], created_at: now, next_action: 'Apply documented platform patterns.' }; return { ...base, digest: require('../../lib/platform-knowledge.cjs').digest(base) }; })(),
    'documentation-skill-validation.v1.schema.json': { schema: 'DocumentationSkillValidation/v1', validation_id: 'doc-validation-quality', work_id: binding.work_id, cycle_id: 'cycle-quality', context_id: 'knowledge-quality', source_revision: binding.source_revision, status: 'pass', official_matches: [{ source_url: 'https://docs.example.test/platform/', result: 'match', evidence_pointer: 'WORK.md#official-docs' }], skill_matches: [{ skill_id: 'target-platform-freedom-ui-frontend-diagnostics', skill_sha256: 'f'.repeat(64), result: 'match', evidence_pointer: 'WORK.md#skills' }], findings: [], evidence_pointers: ['WORK.md#documentation-skill-validation'], validated_by: 'documentation-skill-validator', validated_at: now, next_action: 'Continue to exact-three review.' },
    'skill-change-proposal.v1.schema.json': { schema: 'SkillChangeProposal/v1', proposal_id: 'proposal-quality', skill_id: 'target-platform-freedom-ui-frontend-diagnostics', skill_path: '.codex/skills/target-platform-freedom-ui-frontend-diagnostics/SKILL.md', source_url: 'https://docs.example.test/platform/', source_hash: 'f'.repeat(64), rule: 'Use supported request lifecycle diagnostics.', evidence_pointers: ['WORK.md#skill-proposal'], eval_manifest: 'docs/skill-learning/eval-manifest.schema.json', status: 'proposed', created_at: now, next_action: 'Run source-example, held-out, negative-transfer and regression checks.' },
    'skill-update-result.v1.schema.json': { schema: 'SkillUpdateResult/v1', update_id: 'update-quality', proposal_id: 'proposal-quality', skill_id: 'target-platform-freedom-ui-frontend-diagnostics', status: 'applied', source_hash: 'f'.repeat(64), generated_hash: '1'.repeat(64), checks: [{ id: 'held-out', status: 'pass', pointer: 'docs/skill-learning/validation.md' }], evidence_pointers: ['WORK.md#skill-update'], updated_at: now, next_action: 'Sync marketplace and rerun quality/evals.' }
  };
}
module.exports = { binding, checkpoint, deploymentManifest, fixtures, manifest, now, projectRegistry, ponytailDecision };

