'use strict';

const fs=require('fs'),os=require('os'),path=require('path');
const {execFileSync}=require('child_process');
const runtime=require('../../lib/runtime.cjs');
const {checkpoint,fixtures,projectRegistry,ponytailDecision}=require('./fixtures.cjs');

function repo(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'runtime-project-v4-'));execFileSync('git',['init','-q'],{cwd:root});execFileSync('git',['config','user.email','test@local'],{cwd:root});execFileSync('git',['config','user.name','test'],{cwd:root});fs.mkdirSync(path.join(root,'src'));fs.writeFileSync(path.join(root,'src','a.js'),'a');fs.mkdirSync(path.join(root,'docs','tenants'),{recursive:true});fs.writeFileSync(path.join(root,'docs','tenants','project-registry.v1.json'),JSON.stringify(projectRegistry));fs.mkdirSync(path.join(root,'backlogs','tenants','sample-tenant','projects','sample-project','backlog','tasks'),{recursive:true});execFileSync('git',['add','.'],{cwd:root});execFileSync('git',['commit','-qm','base'],{cwd:root});return root;}
function save(root,value){const dir=path.join(root,'.agent','work',value.work_id);fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,'resume.json');fs.writeFileSync(file,JSON.stringify(value));return file;}
function plan(work='project-work'){return checkpoint({work_id:work,revision:1,lifecycle_state:'PLAN',protocol_version:'agent-development-runtime/v2',allowed_paths:['src/a.js'],fingerprint_paths:['src/a.js'],sealed_at:undefined,sealed_revision:undefined,implementation_fingerprint:undefined});}
function context(revision='provider-r1'){return {schema:'ProjectContext/v1',tenant_id:'sample-tenant',primary_project_id:'sample-project',affected_project_ids:['sample-project'],ledger_id:'project:sample-tenant/sample-project',task_id:'SAMPLE-TENANT-SAMPLE-PROJECT-1',wiki_roots:['docs/tenants/sample-tenant/wiki','docs/tenants/sample-tenant/wiki/Projects/Sample Project'],provider_revision:revision};}
function scope(c){return {schema:'CoordinationScope/v1',work_id:c.work_id,thread_id:'019ffa-test-thread',source_revision:c.source_revision,contour_keys:['tenant:sample-tenant','project:sample-tenant/sample-project','file:src/a.js'],exclusive_resources:['file:src/a.js']};}
function response(task){return {status:0,stdout:JSON.stringify(task),stderr:''};}
function runnerQueue(items,cwds=[]){return (_command,_args,options)=>{cwds.push(options.cwd);const item=items.shift();return item instanceof Error?{status:1,stdout:'',stderr:item.message,error:item}:item;};}
function options(items,cwds){return {runner:runnerQueue(items,cwds),cliExists:false,npxCommand:'npx'};}
function task(revision,status='To Do'){return {id:'SAMPLE-TENANT-SAMPLE-PROJECT-1',updatedAt:revision,status};}
function coordination(work='quality-tooling'){return {schema:'CoordinationBinding/v1',work_id:work,thread_id:'019ffa-test-thread',ticket_id:'ticket-1',generation:1,exclusive_resources:['file:agent-runtime/lib/runtime.cjs'],active_resources:['file:agent-runtime/lib/runtime.cjs'],blocked_resources:[]};}
function projection(ctx,status='Awaiting Testing'){return {schema:'BacklogProjection/v1',ledger_id:ctx.ledger_id,task_id:ctx.task_id,desired_status:status,observed_status:status,provider_revision:ctx.provider_revision,sync_status:'synced',gap_pointer:null,error:null,updated_at:'2026-08-16T12:00:00.000Z'};}
function deliveryCheckpoint(){const f=fixtures(),ctx=context();return checkpoint({protocol_version:'agent-development-runtime/v4',lifecycle_state:'DELIVERY',coordination:coordination(),project_context:ctx,backlog_projection:projection(ctx),user_testing_receipts:[],delivery_cycle_id:'cycle-1',verification_completed_at:'2026-08-16T12:00:00.000Z',delivery_receipt:f['delivery-receipt.v2.schema.json'],runtime_receipt:f['runtime-receipt.v2.schema.json']});}
function testingReceipt(c,decision){return {schema:'UserTestingReceipt/v1',work_id:c.work_id,source_revision:c.source_revision,sealed_revision:c.sealed_revision,implementation_fingerprint:c.implementation_fingerprint,acceptance_manifest_id:c.acceptance_manifest.id,acceptance_manifest_version:c.acceptance_manifest.version,delivery_cycle_id:c.delivery_cycle_id,decision,actor:'user',source:'current-thread',timestamp:'2026-08-16T12:01:00.000Z',sanitized_pointers:[`current-thread#${decision}`]};}

describe('protocol v4 project-aware runtime',()=>{
  test('registers an exact project task, thread and contour and synchronizes In Development',()=>{const root=repo(),base=plan(),file=save(root,base),cwds=[];const backlogOptions=options([response(task('provider-r1')),response(task('provider-r1')),response({}),response(task('provider-r2','In Development'))],cwds);let c=runtime.registerProjectWork(file,{expectedRevision:1,sourceRevision:base.source_revision,root,context:context(),scope:scope(base),backlogOptions});expect(c.protocol_version).toBe('agent-development-runtime/v4');expect(c.coordination.thread_id).toBe('019ffa-test-thread');expect(c.backlog_projection).toMatchObject({desired_status:'In Development',observed_status:'In Development',sync_status:'synced',provider_revision:'provider-r2'});expect(c.project_context.provider_revision).toBe('provider-r2');expect(runtime.coordination.status(root,c.work_id).tickets[0].contour_keys).toEqual(expect.arrayContaining(['tenant:sample-tenant','project:sample-tenant/sample-project']));c=runtime.syncBacklogProjection(file,{expectedRevision:c.revision,sourceRevision:c.source_revision,root,backlogOptions:options([response(task('provider-r2','In Development')),response({}),response(task('provider-r3','In Development'))],cwds)});expect(c.project_context.provider_revision).toBe('provider-r3');expect(c.backlog_projection).toMatchObject({sync_status:'synced',provider_revision:'provider-r3'});expect(new Set(cwds)).toEqual(new Set([path.join(root,'backlogs','tenants','sample-tenant','projects','sample-project','backlog')]));});

  test('upgrades an existing v3 ticket without duplicating it and adds project contours',()=>{const root=repo(),base=plan('upgrade-work'),file=save(root,base),legacyScope={...scope(base),contour_keys:['file:src/a.js']};let c=runtime.registerCoordinationScope(file,{expectedRevision:1,sourceRevision:base.source_revision,root,scope:legacyScope});const backlogOptions=options([response(task('provider-r1')),response(task('provider-r1')),response({}),response(task('provider-r2','In Development'))]);c=runtime.registerProjectWork(file,{expectedRevision:c.revision,sourceRevision:c.source_revision,root,context:context(),backlogOptions});const tickets=runtime.coordination.status(root,c.work_id).tickets;expect(tickets).toHaveLength(1);expect(tickets[0].contour_keys).toEqual(expect.arrayContaining(['tenant:sample-tenant','project:sample-tenant/sample-project']));expect(c.protocol_version).toBe('agent-development-runtime/v4');});

  test('backfills Ponytail policy through the typed v2/v3 operation and blocks v4 registration without it',()=>{
    const root=repo();
    const v2=plan('bind-v2');delete v2.implementation_policy;const v2File=save(root,v2);
    let bound=runtime.bindPonytailPolicy(v2File,{expectedRevision:1,sourceRevision:v2.source_revision,policy:ponytailDecision({work_id:v2.work_id})});
    expect(bound.protocol_version).toBe('agent-development-runtime/v2');
    expect(bound.implementation_policy).toMatchObject({schema:'PonytailPolicyDecision/v1',work_id:v2.work_id,mode:'full',mutation_allowed:true});
    bound=runtime.bindPonytailPolicy(v2File,{expectedRevision:bound.revision,sourceRevision:bound.source_revision,implementationPolicy:ponytailDecision({work_id:v2.work_id})});
    expect(bound.revision).toBe(3);
    const v3={...plan('bind-v3'),protocol_version:'agent-development-runtime/v3',coordination:coordination('bind-v3'),review_dispatch_reservation_ledger:[]};delete v3.implementation_policy;const v3File=save(root,v3);
    bound=runtime.bindPonytailPolicy(v3File,{expectedRevision:1,sourceRevision:v3.source_revision,policy:ponytailDecision({work_id:v3.work_id})});
    expect(bound.protocol_version).toBe('agent-development-runtime/v3');
    expect(bound.implementation_policy.work_id).toBe(v3.work_id);
    const missing=plan('missing-v4-policy');delete missing.implementation_policy;const missingFile=save(root,missing);
    expect(()=>runtime.registerProjectWork(missingFile,{expectedRevision:1,sourceRevision:missing.source_revision,root,context:context(),scope:scope(missing),backlogOptions:options([response(task('provider-r1'))])})).toThrow(/v4 Ponytail policy binding required/);
    expect(runtime.coordination.status(root,missing.work_id).tickets).toHaveLength(0);
  });

  test('fails closed for unknown protocol and invalid registry/task/wiki bindings',()=>{expect(()=>runtime.assertCheckpoint({...checkpoint(),protocol_version:'agent-development-runtime/v5'})).toThrow(/unsupported/);const root=repo(),base=plan(),file=save(root,base),good={expectedRevision:1,sourceRevision:base.source_revision,root,scope:scope(base),backlogOptions:options([])};for(const changed of [{tenant_id:'other'},{task_id:'SAMPLE-TENANT-SAMPLE-PROJECT-X'},{ledger_id:'project:sample-tenant/wrong'},{wiki_roots:['docs/tenants/sample-tenant/wiki']}])expect(()=>runtime.registerProjectWork(file,{...good,context:{...context(),...changed}})).toThrow(/project|registry|ledger|wiki/i);expect(()=>runtime.assertCheckpoint({...deliveryCheckpoint(),project_context:undefined})).toThrow(/context/);});

  test('records provider failure as a GAP without changing lifecycle authority',()=>{const root=repo(),base=plan(),file=save(root,base),backlogOptions=options([response(task('provider-r1')),new Error('provider unavailable')]);const c=runtime.registerProjectWork(file,{expectedRevision:1,sourceRevision:base.source_revision,root,context:context(),scope:scope(base),backlogOptions});expect(c.lifecycle_state).toBe('PLAN');expect(c.backlog_projection).toMatchObject({desired_status:'In Development',sync_status:'failed',gap_pointer:'GAP-BACKLOG-SYNC-001'});expect(c.source_plan.gaps).toContain('GAP-BACKLOG-SYNC-001');});

  test('projects user testing start and acceptance while feedback returns only this work to EXECUTE',()=>{const root=repo(),file=save(root,deliveryCheckpoint());let c=JSON.parse(fs.readFileSync(file,'utf8'));c=runtime.recordUserTestingReceipt(file,testingReceipt(c,'started'),c.revision,c.source_revision);expect(c.lifecycle_state).toBe('DELIVERY');expect(c.backlog_projection.desired_status).toBe('Testing');c=runtime.recordUserTestingReceipt(file,testingReceipt(c,'accepted'),c.revision,c.source_revision);expect(c.user_testing_receipts.map(x=>x.decision)).toEqual(['started','accepted']);expect(c.backlog_projection.desired_status).toBe('Testing');expect(()=>runtime.recordUserTestingReceipt(file,testingReceipt(c,'accepted'),c.revision,c.source_revision)).toThrow(/final|replay/);const feedbackFile=save(root,{...deliveryCheckpoint(),work_id:'feedback-work',implementation_policy:ponytailDecision({work_id:'feedback-work'}),coordination:coordination('feedback-work')});const f=JSON.parse(fs.readFileSync(feedbackFile,'utf8'));const corrected=runtime.recordUserTestingReceipt(feedbackFile,testingReceipt(f,'feedback'),f.revision,f.source_revision);expect(corrected.lifecycle_state).toBe('EXECUTE');expect(corrected.backlog_projection.desired_status).toBe('Returned for Rework');expect(corrected.delivery_receipt).toBeNull();expect(corrected.user_testing_feedback_receipt.decision).toBe('feedback');});

  test('requires current user testing acceptance before v4 completion',()=>{const root=repo(),c=deliveryCheckpoint(),file=save(root,c);expect(()=>runtime.completeWork(file,{expectedRevision:c.revision,sourceRevision:c.source_revision,root})).toThrow(/user testing acceptance/);});

  test('v4 checkpoint and public verbs fail closed for missing ledgers, bindings, states and replay',()=>{
    const root=repo(),base=deliveryCheckpoint();
    const missingLedger={...base};delete missingLedger.user_testing_receipts;expect(()=>runtime.assertCheckpoint(missingLedger,root)).toThrow(/user testing receipt ledger/);
    const missingContext={...base};delete missingContext.project_context;expect(()=>runtime.assertCheckpoint(missingContext,root)).toThrow(/project registry\/context/);
    expect(()=>runtime.assertCheckpoint({...base,user_testing_receipts:[{...testingReceipt(base,'started'),actor:''}]},root)).toThrow(/attribution/);
    const v2=plan('sync-v2'),v2File=save(root,v2);expect(()=>runtime.syncBacklogProjection(v2File,{expectedRevision:v2.revision,sourceRevision:v2.source_revision,root})).toThrow(/protocol v4/);
    const delivered=save(root,{...base,work_id:'wrong-testing-state',implementation_policy:ponytailDecision({work_id:'wrong-testing-state'}),coordination:coordination('wrong-testing-state'),lifecycle_state:'VERIFY'});expect(()=>runtime.recordUserTestingReceipt(delivered,testingReceipt({...base,work_id:'wrong-testing-state'},'started'),base.revision,base.source_revision)).toThrow(/requires delivered/);
    const invalidReceiptFile=save(root,base);expect(()=>runtime.recordUserTestingReceipt(invalidReceiptFile,{...testingReceipt(base,'started'),actor:''},base.revision,base.source_revision)).toThrow(/attribution/);
    const replayFile=save(root,{...base,work_id:'testing-replay',implementation_policy:ponytailDecision({work_id:'testing-replay'}),coordination:coordination('testing-replay')});let replay=JSON.parse(fs.readFileSync(replayFile,'utf8'));replay=runtime.recordUserTestingReceipt(replayFile,testingReceipt(replay,'started'),replay.revision,replay.source_revision);expect(()=>runtime.recordUserTestingReceipt(replayFile,testingReceipt(replay,'started'),replay.revision,replay.source_revision)).toThrow(/replay/);
  });

  test('registration rejects incomplete contour, unavailable initial task and already-bound v2 plan',()=>{
    const incompleteRoot=repo(),incomplete=plan('incomplete-contour'),incompleteFile=save(incompleteRoot,incomplete),badScope={...scope(incomplete),contour_keys:['file:src/a.js']};expect(()=>runtime.registerProjectWork(incompleteFile,{expectedRevision:1,sourceRevision:incomplete.source_revision,root:incompleteRoot,context:context(),scope:badScope,backlogOptions:options([response(task('provider-r1'))])})).toThrow(/project coordination contour/);
    const absentRoot=repo(),absent=plan('absent-provider'),absentFile=save(absentRoot,absent);expect(()=>runtime.registerProjectWork(absentFile,{expectedRevision:1,sourceRevision:absent.source_revision,root:absentRoot,context:context(),scope:scope(absent),backlogOptions:options([new Error('offline')])})).toThrow(/task\/revision/);
    const boundRoot=repo(),bound=plan('already-bound'),boundFile=save(boundRoot,{...bound,coordination:coordination('already-bound')});expect(()=>runtime.registerProjectWork(boundFile,{expectedRevision:1,sourceRevision:bound.source_revision,root:boundRoot,context:context(),scope:scope(bound),backlogOptions:options([response(task('provider-r1'))])})).toThrow(/v2 unbound/);
    const wrongStateRoot=repo(),wrongState={...plan('registration-state'),lifecycle_state:'TRACE'},wrongStateFile=save(wrongStateRoot,wrongState);expect(()=>runtime.registerProjectWork(wrongStateFile,{expectedRevision:1,sourceRevision:wrongState.source_revision,root:wrongStateRoot,context:context(),scope:scope(wrongState),backlogOptions:options([])})).toThrow(/unbound plan/);
    const alreadyProjectRoot=repo(),alreadyProject={...plan('registration-project'),project_context:context()},alreadyProjectFile=save(alreadyProjectRoot,alreadyProject);expect(()=>runtime.registerProjectWork(alreadyProjectFile,{expectedRevision:1,sourceRevision:alreadyProject.source_revision,root:alreadyProjectRoot,context:context(),scope:scope(alreadyProject),backlogOptions:options([])})).toThrow(/unbound plan/);
  });

  test('uses the closed lifecycle-to-Backlog projection without making Backlog authoritative',()=>{const base={lifecycle_state:'PLAN',reviews:[],verification:[],question_candidates:[],user_testing_receipts:[]};const cases=[[{...base,lifecycle_state:'INTAKE'},'To Do'],[base,'In Development'],[{...base,lifecycle_state:'VERIFY'},'In Review'],[{...base,lifecycle_state:'VERIFY',reviews:[1,2,3],verification:[1,2,3]},'Ready for Delivery'],[{...base,lifecycle_state:'DELIVERY'},'Ready for Delivery'],[{...base,lifecycle_state:'DELIVERY',delivery_receipt:{}},'Awaiting Testing'],[{...base,lifecycle_state:'DELIVERY',delivery_receipt:{},user_testing_receipts:[{decision:'started'}]},'Testing'],[{...base,lifecycle_state:'EXECUTE',user_testing_feedback_receipt:{decision:'feedback'}},'Returned for Rework'],[{...base,lifecycle_state:'COMPLETE'},'Done'],[{...base,question_candidates:[{blocking:true,status:'open'}]},'Blocked']];for(const [input,status] of cases)expect(runtime.projects.desiredStatus(input)).toBe(status);});

  test('persisted v4 validation independently enforces registry, projection, attribution and coordination',()=>{
    const root=repo(),base=deliveryCheckpoint(),receipt=testingReceipt(base,'started');
    expect(()=>runtime.assertCheckpoint({...base,implementation_policy:ponytailDecision({work_id:'other-policy-work'})},root)).toThrow(/Ponytail policy work binding invalid/);
    expect(()=>runtime.assertCheckpoint({...base,coordination:{...base.coordination,schema:'Wrong/v1'}},root)).toThrow(/^v4 coordination binding invalid$/);
    expect(()=>runtime.assertCheckpoint({...base,project_context:{...base.project_context,wiki_roots:['docs/tenants/sample-tenant/wiki']}},root)).toThrow(/^v4 project registry\/context binding invalid$/);
    expect(()=>runtime.assertCheckpoint({...base,backlog_projection:{...base.backlog_projection,task_id:'SAMPLE-TENANT-SAMPLE-PROJECT-2'}},root)).toThrow(/^v4 project registry\/context binding invalid$/);
    expect(()=>runtime.assertCheckpoint({...base,user_testing_receipts:[{...receipt,timestamp:'not-a-time'}]},root)).toThrow(/^user testing timestamp invalid$/);
    expect(()=>runtime.assertCheckpoint({...base,user_testing_receipts:[{...receipt,sanitized_pointers:['secret://not-allowed']}]},root)).toThrow(/^sanitized pointer invalid$/);
    expect(()=>runtime.validateContinuity(base,{expectedRevision:base.revision,sourceRevision:base.source_revision,root})).toThrow(/coordination|ledger|ticket|claim/i);
  });
});

