'use strict';

// Synthetic assurance scenarios use only public typed runtime operations and
// temporary Git repositories.  They exercise route metadata without creating
// product work records or claiming policy semantics that the runtime cannot
// yet type-check (external ledger task target-platformn and probe authority).
const fs=require('fs');
const os=require('os');
const path=require('path');
const {execFileSync}=require('child_process');
const runtime=require('../../lib/runtime.cjs');
const backlog=require('../../lib/backlog-adapter.cjs');
const {checkpoint,deploymentManifest,fixtures,projectRegistry}=require('./fixtures.cjs');

function repo(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'runtime-scenarios-'));execFileSync('git',['init','-q'],{cwd:root});execFileSync('git',['config','user.email','scenario@example.test'],{cwd:root});execFileSync('git',['config','user.name','scenario'],{cwd:root});fs.mkdirSync(path.join(root,'src'));fs.writeFileSync(path.join(root,'src','flow.txt'),'base\n');fs.mkdirSync(path.join(root,'docs','tenants'),{recursive:true});fs.writeFileSync(path.join(root,'docs','tenants','project-registry.v1.json'),JSON.stringify(projectRegistry));fs.mkdirSync(path.join(root,'backlogs','tenants','sample-tenant','projects','sample-project','backlog','tasks'),{recursive:true});execFileSync('git',['add','.'],{cwd:root});execFileSync('git',['commit','-qm','base'],{cwd:root});return root;}
function save(root,c){const dir=path.join(root,'.agent','work',c.work_id);fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,'resume.json');fs.writeFileSync(file,JSON.stringify(c));return file;}
function future(){return new Date(Date.now()+1000).toISOString();}
function initial(route,kind,risk,work){const c=checkpoint({work_id:work,revision:1,lifecycle_state:'INTAKE',route,change_kind:kind,risk,allowed_paths:['src/flow.txt'],fingerprint_paths:['src/flow.txt'],sealed_at:undefined,sealed_revision:undefined,implementation_fingerprint:undefined,review_generation:0,review_generation_ledger:[],question_candidates:[]});return {...c,acceptance_manifest:{...c.acceptance_manifest,source_revision:c.source_revision}};}
function binding(c){return {work_id:c.work_id,source_revision:c.source_revision,sealed_revision:c.sealed_revision,implementation_fingerprint:c.implementation_fingerprint,acceptance_manifest_id:c.acceptance_manifest.id,acceptance_manifest_version:c.acceptance_manifest.version};}
function packet(c,generation=1){return {schema:'BlindReviewPacket/v2',status:'frozen',packet_id:`packet-${c.work_id}-${generation}`,packet_version:1,wave:generation,generation,...binding(c),required_profile:{model:'configured',reasoning:'high'},review_scope:{paths:c.fingerprint_paths,absence_assertions:{}},profile_attestation_set:`dispatch-${generation}.json`};}
function reservation(c,p){return {schema:'ReviewDispatchReservation/v1',status:'complete',...binding(c),packet_id:p.packet_id,packet_version:p.packet_version,wave:p.wave,generation:p.generation,requested_model:'configured',requested_reasoning_effort:'high',reserved_at:future(),entries:runtime.lenses.map((lens,n)=>({handle_id:`handle-${p.generation}-${n}`,task_id:`task-${p.generation}-${n}`,dispatch_id:`dispatch-${p.generation}-${n}`,reviewer_id:`reviewer-${p.generation}-${n}`,lens}))};}
function dispatch(c,p,verified=true){return {schema:'DispatchProfileAttestationSet/v1',...binding(c),packet_id:p.packet_id,packet_version:p.packet_version,wave:p.wave,orchestrator:'scenario-root',selector_source:'scenario',requested_model:'configured',requested_reasoning_effort:'high',runtime_metadata_observed:false,issued_at:future(),root_task_id:'root-task',root_dispatch_id:'root-dispatch',entries:runtime.lenses.map((lens,n)=>({task_id:`task-${p.generation}-${n}`,dispatch_id:`dispatch-${p.generation}-${n}`,reviewer_id:`reviewer-${p.generation}-${n}`,lens,profile_verified:verified,profile_verification:verified?{verified_model:'configured',verified_reasoning_effort:'high',verification_source:'tests/profile',verification_pointer:`tests/profile-${n}`,verified_at:future()}:undefined}))};}
function review(c,p,n,verdict='clean'){return {schema:'ReviewReceipt/v2',...binding(c),reviewer_id:`reviewer-${p.generation}-${n}`,dispatch_task_id:`task-${p.generation}-${n}`,dispatch_id:`dispatch-${p.generation}-${n}`,lens:runtime.lenses[n],history_isolation:true,findings:verdict==='clean'?[]:['bounded finding'],verdict,packet_id:p.packet_id,packet_version:p.packet_version,wave:p.wave};}
function reverse(c,p,n){return {schema:'ReverseValidationReceipt/v1',...binding(c),receipt_id:`reverse-${p.generation}-${n}`,reviewer_id:`reverse-${p.generation}-${n}`,type:['trace_scope','technical_safety','evidence_truth'][n],verdict:'pass',validator:'scenario',timestamp:future(),evidence:['tests/scenario'],ac_refs:['AC-QUALITY-1'],packet_id:p.packet_id,packet_version:p.packet_version};}
function evidence(c,id,kind='Static',extra={}){return {schema:'Evidence/v1',...binding(c),id,class:kind,pointer:`tests/${id}`,timestamp:future(),ac_refs:['AC-QUALITY-1'],...extra};}
function recovery(c){return {schema:'RecoveryEvidence/v1',...binding(c),id:'recovery',action:'rollback drill',actor:'scenario',attribution:'tests/recovery',result:'pass',rollback:'revert',timestamp:future(),ac_refs:['AC-QUALITY-1']};}
function plan(root,c,file){let n=runtime.beginTrace(file,{expectedRevision:c.revision,sourceRevision:c.source_revision});n=runtime.replanWork(file,{expectedRevision:n.revision,sourceRevision:n.source_revision,sourcePlan:{...n.source_plan,scope:'synthetic bounded scenario'},acceptance:n.acceptance,testPlan:['synthetic scenario'],acceptanceManifest:n.acceptance_manifest});n=runtime.beginExecution(file,{expectedRevision:n.revision,sourceRevision:n.source_revision,approval:{source_revision:n.source_revision,pointer:'WORK.md#scenario-approval'}});fs.writeFileSync(path.join(root,'src','flow.txt'),`${n.work_id}\n`);return runtime.sealMutation(file,n.revision,n.source_revision,root);}
function backlogResponse(task){return {status:0,stdout:JSON.stringify(task),stderr:''};}
function backlogOptions(items){return {runner:()=>items.shift(),cliExists:false,npxCommand:'npx'};}
function backlogTask(revision,status='To Do'){return {id:'SAMPLE-TENANT-SAMPLE-PROJECT-1',updatedAt:revision,status};}
function projectContext(revision='provider-r1'){return {schema:'ProjectContext/v1',tenant_id:'sample-tenant',primary_project_id:'sample-project',affected_project_ids:['sample-project'],ledger_id:'project:sample-tenant/sample-project',task_id:'SAMPLE-TENANT-SAMPLE-PROJECT-1',wiki_roots:['docs/tenants/sample-tenant/wiki','docs/tenants/sample-tenant/wiki/Projects/Sample Project'],provider_revision:revision};}
function projectScope(c){return {schema:'CoordinationScope/v1',work_id:c.work_id,thread_id:'019ffa-scenario-v4',source_revision:c.source_revision,contour_keys:['tenant:sample-tenant','project:sample-tenant/sample-project','br:BR-QUALITY','sr:SR-QUALITY-1','file:src/flow.txt'],exclusive_resources:['file:src/flow.txt']};}
function planV4(root,c,file){let n=runtime.beginTrace(file,{expectedRevision:c.revision,sourceRevision:c.source_revision});n=runtime.replanWork(file,{expectedRevision:n.revision,sourceRevision:n.source_revision,sourcePlan:{...n.source_plan,scope:'synthetic project-aware scenario'},acceptance:n.acceptance,testPlan:['synthetic scenario'],acceptanceManifest:n.acceptance_manifest});n=runtime.registerProjectWork(file,{expectedRevision:n.revision,sourceRevision:n.source_revision,root,context:projectContext(),scope:projectScope(n),backlogOptions:backlogOptions([backlogResponse(backlogTask('provider-r1')),backlogResponse(backlogTask('provider-r1')),backlogResponse({}),backlogResponse(backlogTask('provider-r2','In Development'))])});n=runtime.claimCoordinationResources(file,{expectedRevision:n.revision,sourceRevision:n.source_revision,root,resources:['file:src/flow.txt'],lease_expires_at:new Date(Date.now()+60000).toISOString()});n=runtime.beginExecution(file,{expectedRevision:n.revision,sourceRevision:n.source_revision,approval:{source_revision:n.source_revision,pointer:'WORK.md#scenario-approval'}});fs.writeFileSync(path.join(root,'src','flow.txt'),`${n.work_id}\n`);return runtime.sealMutation(file,n.revision,n.source_revision,root);}
function verified(c,file,root,generation=1){const p=packet(c,generation);let n=runtime.freezeReviewPacket(file,p,c.revision,c.source_revision);if(['agent-development-runtime/v3','agent-development-runtime/v4'].includes(n.protocol_version))n=runtime.recordReviewDispatchReservation(file,reservation(n,p),n.revision,n.source_revision);n=runtime.recordDispatchAttestationSet(file,dispatch(n,p),n.revision,n.source_revision,root);for(let i=0;i<3;i++)n=runtime.recordReviewReceipt(file,review(n,p,i),n.revision,n.source_revision,root);for(let i=0;i<3;i++)n=runtime.recordReverseValidationReceipt(file,reverse(n,p,i),n.revision,n.source_revision,root);return {state:n,packet:p};}
function approved(c,file,root,status,blocking=false){let n=runtime.advanceToDelivery(file,{expectedRevision:c.revision,sourceRevision:c.source_revision,root});const delivery={schema:'DeliveryReceipt/v2',...binding(n),delivery_cycle_id:n.delivery_cycle_id,decision:'approved',actor:'owner',source:'synthetic',timestamp:future(),sanitized_pointers:['WORK.md#approval'],deployment_manifest:deploymentManifest(n,'src/flow.txt')};n=runtime.recordDeliveryReceipt(file,delivery,n.revision,n.source_revision);const receipt={schema:'RuntimeReceipt/v2',...binding(n),status,blocking,environment:'test',actor:'scenario',timestamp:future(),ac_refs:['AC-QUALITY-1'],sanitized_pointers:status==='accepted'?['runtime/accepted']:[],...(status==='deferred'||status==='pending'||status==='failed'?{gap_or_defect_pointer:'GAP-SYNTHETIC-001'}:{})};n=runtime.recordRuntimeReceipt(file,receipt,n.revision,n.source_revision);return n;}

describe('synthetic public runtime scenario matrix',()=>{
  test('R0 remains read-only after trace',()=>{const root=repo(),c=initial('R0','documentation','low','syn-r0'),file=save(root,c),trace=runtime.beginTrace(file,{expectedRevision:1,sourceRevision:c.source_revision});expect(trace.lifecycle_state).toBe('TRACE');expect(()=>runtime.replanWork(file,{expectedRevision:trace.revision,sourceRevision:trace.source_revision,sourcePlan:trace.source_plan,acceptance:trace.acceptance,testPlan:trace.test_plan,acceptanceManifest:trace.acceptance_manifest})).toThrow(/R0 evidence route/);expect(fs.readFileSync(file,'utf8')).toContain('"TRACE"');});

  test('R1 documentation completes with nonblocking not_required runtime',()=>{const root=repo(),c=initial('R1','documentation','low','syn-r1'),file=save(root,c),sealed=plan(root,c,file),set=verified(sealed,file,root),delivery=approved(set.state,file,root,'not_required');expect(runtime.validateGate(delivery,'ship:pre',{expectedRevision:delivery.revision,sourceRevision:delivery.source_revision,root})).toBe(true);expect(runtime.completeWork(file,{expectedRevision:delivery.revision,sourceRevision:delivery.source_revision,root}).lifecycle_state).toBe('COMPLETE');});

  test.each(['deferred','pending'])('R2 defect completes with nonblocking %s runtime GAP',status=>{const root=repo(),c=initial('R2','defect','medium',`syn-r2-${status}`),file=save(root,c),sealed=plan(root,c,file),set=verified(sealed,file,root),delivery=approved(set.state,file,root,status);expect(runtime.completeWork(file,{expectedRevision:delivery.revision,sourceRevision:delivery.source_revision,root}).runtime_receipt).toMatchObject({status,blocking:false,gap_or_defect_pointer:'GAP-SYNTHETIC-001'});});

  test('R3 high-risk correction requires a fresh packet/profile/review set before accepted completion',()=>{const root=repo(),c=initial('R3','feature','high','syn-r3'),file=save(root,c);let n=plan(root,c,file),p=packet(n);n=runtime.freezeReviewPacket(file,p,n.revision,n.source_revision);expect(()=>runtime.recordDispatchAttestationSet(file,dispatch(n,p,false),n.revision,n.source_revision,root)).toThrow(/profile verification/);n=runtime.recordDispatchAttestationSet(file,dispatch(n,p),n.revision,n.source_revision,root);n=runtime.recordReviewReceipt(file,review(n,p,0,'changes_required'),n.revision,n.source_revision,root);n=runtime.beginCorrection(file,{expectedRevision:n.revision,sourceRevision:n.source_revision,correction:{reason:'review finding',pointer:'WORK.md#correction'}});expect(n).toMatchObject({lifecycle_state:'EXECUTE',reviews:[],verification:[],review_packet:null});fs.writeFileSync(path.join(root,'src','flow.txt'),'corrected\n');n=runtime.sealMutation(file,n.revision,n.source_revision,root);const set=verified(n,file,root,2);n=runtime.recordRecoveryEvidence(file,recovery(set.state),set.state.revision,set.state.source_revision);n=runtime.recordEvidence(file,evidence(n,'runtime','Runtime',{closes_runtime:true,actor:'scenario'}),n.revision,n.source_revision);n=approved(n,file,root,'accepted',true);expect(runtime.completeWork(file,{expectedRevision:n.revision,sourceRevision:n.source_revision,root}).lifecycle_state).toBe('COMPLETE');});

  test('R4 incident retains generic probe evidence while linked-defect policy stays explicit',()=>{const root=repo(),c=initial('R4','incident','high','syn-r4'),file=save(root,c);let n=plan(root,c,file),set=verified(n,file,root);n=runtime.recordRecoveryEvidence(file,recovery(set.state),set.state.revision,set.state.source_revision);n=runtime.recordEvidence(file,evidence(n,'bounded-probe','Code'),n.revision,n.source_revision);n=runtime.recordEvidence(file,evidence(n,'runtime','Runtime',{closes_runtime:true,actor:'scenario'}),n.revision,n.source_revision);n=approved(n,file,root,'accepted',true);expect(runtime.completeWork(file,{expectedRevision:n.revision,sourceRevision:n.source_revision,root}).lifecycle_state).toBe('COMPLETE');expect(typeof runtime.recordArchitectDecision).toBe('function');expect(runtime.recordLinkedDefect).toBeUndefined();});

  test('protocol v4 completes only after project registration, user acceptance and Done synchronization',()=>{const root=repo(),c=initial('R2','feature','medium','syn-v4-project'),file=save(root,c),sealed=planV4(root,c,file),set=verified(sealed,file,root);let n=approved(set.state,file,root,'not_required');const accepted={schema:'UserTestingReceipt/v1',...binding(n),delivery_cycle_id:n.delivery_cycle_id,decision:'accepted',actor:'user',source:'current-thread',timestamp:future(),sanitized_pointers:['current-thread#accepted']};n=runtime.recordUserTestingReceipt(file,accepted,n.revision,n.source_revision);expect(n.backlog_projection.desired_status).toBe('Testing');n=runtime.completeWork(file,{expectedRevision:n.revision,sourceRevision:n.source_revision,root,backlogOptions:backlogOptions([backlogResponse(backlogTask('provider-r2','In Development')),backlogResponse({}),backlogResponse(backlogTask('provider-r3','Done'))])});expect(n).toMatchObject({lifecycle_state:'COMPLETE',project_context:{provider_revision:'provider-r3'},backlog_projection:{desired_status:'Done',observed_status:'Done',sync_status:'synced',provider_revision:'provider-r3'}});});

  test.each(['feedback','rejected'])('fresh DELIVERY %s returns to a clean EXECUTE correction cycle',decision=>{const root=repo(),c=initial('R2','defect','medium',`syn-delivery-${decision}`),file=save(root,c),sealed=plan(root,c,file),set=verified(sealed,file,root);let n=runtime.advanceToDelivery(file,{expectedRevision:set.state.revision,sourceRevision:set.state.source_revision,root});expect(n).toMatchObject({lifecycle_state:'DELIVERY',delivery_cycle_id:`delivery-r${set.state.revision+1}`,next_action:'Present current delivery evidence for human decision.'});const receipt={schema:'DeliveryReceipt/v2',...binding(n),delivery_cycle_id:n.delivery_cycle_id,decision,actor:'owner',source:'synthetic',timestamp:future(),sanitized_pointers:[`WORK.md#${decision}`],deployment_manifest:deploymentManifest(n,'src/flow.txt')};n=runtime.recordDeliveryReceipt(file,receipt,n.revision,n.source_revision);expect(n).toMatchObject({lifecycle_state:'EXECUTE',implementation_fingerprint:undefined,sealed_at:null,sealed_revision:null,review_packet:null,reviews:[],verification:[],evidence:[],recovery_evidence:[],delivery_receipt:null,runtime_receipt:null,delivery_feedback_receipt:receipt,correction:{reason:`Human delivery decision: ${decision}`,pointer:`WORK.md#${decision}`}});expect(()=>runtime.recordRuntimeReceipt(file,{schema:'RuntimeReceipt/v2'},n.revision,n.source_revision)).toThrow(/delivery approval/);});

  test('delivery transition and receipt verbs preserve exact wrong-state boundaries without changing persisted bytes',()=>{const root=repo(),c=initial('R2','defect','medium','syn-delivery-state'),file=save(root,c),sealed=plan(root,c,file),set=verified(sealed,file,root),wrongAdvance={...set.state,lifecycle_state:'PLAN'};fs.writeFileSync(file,JSON.stringify(wrongAdvance));const beforeAdvance=fs.readFileSync(file,'utf8');expect(()=>runtime.advanceToDelivery(file,{expectedRevision:wrongAdvance.revision,sourceRevision:wrongAdvance.source_revision,root})).toThrow(/^delivery transition requires verify$/);expect(fs.readFileSync(file,'utf8')).toBe(beforeAdvance);const wrongReceipt={...set.state,lifecycle_state:'VERIFY',delivery_cycle_id:'cycle-wrong-state',verification_completed_at:new Date().toISOString()},receipt={schema:'DeliveryReceipt/v2',...binding(wrongReceipt),delivery_cycle_id:wrongReceipt.delivery_cycle_id,decision:'approved',actor:'owner',source:'synthetic',timestamp:future(),sanitized_pointers:['WORK.md#approval']};fs.writeFileSync(file,JSON.stringify(wrongReceipt));const beforeReceipt=fs.readFileSync(file,'utf8');expect(()=>runtime.recordDeliveryReceipt(file,receipt,wrongReceipt.revision,wrongReceipt.source_revision)).toThrow(/^delivery receipt requires delivery state$/);expect(fs.readFileSync(file,'utf8')).toBe(beforeReceipt);});

  test('runtime recording and completion retain independent delivery, clarification and shipment guards',()=>{const root=repo(),c=initial('R2','defect','medium','syn-runtime-complete'),file=save(root,c),sealed=plan(root,c,file),set=verified(sealed,file,root);let delivery=runtime.advanceToDelivery(file,{expectedRevision:set.state.revision,sourceRevision:set.state.source_revision,root});const approval={schema:'DeliveryReceipt/v2',...binding(delivery),delivery_cycle_id:delivery.delivery_cycle_id,decision:'approved',actor:'owner',source:'synthetic',timestamp:future(),sanitized_pointers:['WORK.md#approval'],deployment_manifest:deploymentManifest(delivery,'src/flow.txt')};delivery=runtime.recordDeliveryReceipt(file,approval,delivery.revision,delivery.source_revision);const receipt={schema:'RuntimeReceipt/v2',...binding(delivery),status:'not_required',blocking:false,environment:'test',actor:'scenario',timestamp:future(),ac_refs:['AC-QUALITY-1'],sanitized_pointers:[]};const wrongState={...delivery,lifecycle_state:'VERIFY'};fs.writeFileSync(file,JSON.stringify(wrongState));let before=fs.readFileSync(file,'utf8');expect(()=>runtime.recordRuntimeReceipt(file,receipt,wrongState.revision,wrongState.source_revision)).toThrow(/^runtime receipt requires delivery approval$/);expect(fs.readFileSync(file,'utf8')).toBe(before);fs.writeFileSync(file,JSON.stringify(delivery));const ready=runtime.recordRuntimeReceipt(file,receipt,delivery.revision,delivery.source_revision);const blocking={...fixtures()['question-candidate.v1.schema.json'],work_id:ready.work_id,source_revision:ready.source_revision};const withQuestion={...ready,question_candidates:[blocking]};fs.writeFileSync(file,JSON.stringify(withQuestion));before=fs.readFileSync(file,'utf8');expect(()=>runtime.completeWork(file,{expectedRevision:withQuestion.revision,sourceRevision:withQuestion.source_revision,root})).toThrow(/^blocking clarification remains open$/);expect(fs.readFileSync(file,'utf8')).toBe(before);const withoutRuntime={...ready,runtime_receipt:null};fs.writeFileSync(file,JSON.stringify(withoutRuntime));before=fs.readFileSync(file,'utf8');expect(()=>runtime.completeWork(file,{expectedRevision:withoutRuntime.revision,sourceRevision:withoutRuntime.source_revision,root})).toThrow(/^runtime receipt invalid$/);expect(fs.readFileSync(file,'utf8')).toBe(before);});

  test('correction input guards reject wrong state, missing fields, unsafe pointers and invalid replacement manifests',()=>{const root=repo(),base=initial('R2','defect','medium','syn-correction-guards'),verify={...base,lifecycle_state:'VERIFY',sealed_at:new Date().toISOString(),sealed_revision:1,implementation_fingerprint:'a'.repeat(64)},cases=[{state:base,input:{correction:{reason:'bounded',pointer:'WORK.md#correction'}},error:/^bounded correction contract required$/},{state:verify,input:{},error:/^bounded correction contract required$/},{state:verify,input:{correction:{reason:'',pointer:'WORK.md#correction'}},error:/^correction reason missing$/},{state:verify,input:{correction:{reason:'bounded',pointer:''}},error:/^correction pointer missing$/},{state:verify,input:{correction:{reason:'bounded',pointer:'secret=value'}},error:/^sanitized pointer invalid$/}];for(const [index,{state,input,error}] of cases.entries()){const current={...state,work_id:`syn-correction-guard-${index}`},file=save(root,current),before=fs.readFileSync(file,'utf8');expect(()=>runtime.beginCorrection(file,{expectedRevision:current.revision,sourceRevision:current.source_revision,...input})).toThrow(error);expect(fs.readFileSync(file,'utf8')).toBe(before);}const valid={...verify,work_id:'syn-correction-manifest'},file=save(root,valid),badManifest={...valid.acceptance_manifest,source:'',source_revision:valid.source_revision};expect(()=>runtime.beginCorrection(file,{expectedRevision:valid.revision,sourceRevision:valid.source_revision,correction:{reason:'bounded',pointer:'WORK.md#correction'},acceptanceManifest:badManifest})).toThrow(/^manifest source missing$/);const delivery={...verify,work_id:'syn-correction-delivery',lifecycle_state:'DELIVERY'},deliveryFile=save(root,delivery);expect(runtime.beginCorrection(deliveryFile,{expectedRevision:delivery.revision,sourceRevision:delivery.source_revision,correction:{reason:'bounded',pointer:'WORK.md#correction'}}).lifecycle_state).toBe('EXECUTE');});

  test('architect escalation completes only after architect-separated correction and a fresh full review cycle',()=>{const root=repo(),c=initial('R3','feature','high','syn-architect'),file=save(root,c);let n=plan(root,c,file),p=packet(n);n=runtime.freezeReviewPacket(file,p,n.revision,n.source_revision);n=runtime.recordDispatchAttestationSet(file,dispatch(n,p),n.revision,n.source_revision,root);const escalated={...review(n,p,0,'changes_required'),receipt_id:'architect-receipt',finding_objects:[{finding_id:'architect-finding',summary:'Cross-scope impact requires architecture direction.',escalation:'cross_scope'}]};n=runtime.recordReviewReceipt(file,escalated,n.revision,n.source_revision,root);expect(runtime.architectEscalationRequired(n)).toBe(true);expect(()=>runtime.beginCorrection(file,{expectedRevision:n.revision,sourceRevision:n.source_revision,correction:{reason:'cross-scope finding',pointer:'WORK.md#correction'}})).toThrow(/architect decision/);const decision={schema:'ArchitectDecision/v1',...binding(n),decision_id:'architect-decision',review_generation:n.review_generation,packet_id:p.packet_id,packet_version:p.packet_version,wave:p.wave,trigger_receipt_ids:['architect-receipt'],trigger_finding_ids:['architect-finding'],scope:'cross_scope',architect_id:'architect-1',profile_verified:true,architect_profile:{model:'configured',reasoning:'high',verification_source:'tests/architect-profile',verification_pointer:'tests/architect-profile',verified_at:future()},implementer_id:'executor-1',decision:'Apply the smallest root-cause correction.',decision_pointer:'WORK.md#architect-decision',correction_pointer:'WORK.md#architect-correction',timestamp:future(),architect_not_reviewer_or_implementer:true};n=runtime.recordArchitectDecision(file,decision,n.revision,n.source_revision);n=runtime.beginCorrection(file,{expectedRevision:n.revision,sourceRevision:n.source_revision,correction:{reason:'architect direction',pointer:'WORK.md#architect-correction',implementer_id:'executor-1',approved_by:'owner'}});fs.writeFileSync(path.join(root,'src','flow.txt'),'architect-corrected\n');n=runtime.sealMutation(file,n.revision,n.source_revision,root);const fresh=verified(n,file,root,2);expect(fresh.packet).toMatchObject({generation:2,packet_version:1});n=runtime.recordRecoveryEvidence(file,recovery(fresh.state),fresh.state.revision,fresh.state.source_revision);n=runtime.recordEvidence(file,evidence(n,'runtime','Runtime',{closes_runtime:true,actor:'scenario'}),n.revision,n.source_revision);n=approved(n,file,root,'accepted',true);expect(runtime.completeWork(file,{expectedRevision:n.revision,sourceRevision:n.source_revision,root}).lifecycle_state).toBe('COMPLETE');});

  test('unavailable or terminal Backlog ledger state cannot advance delivery or replace its receipts',()=>{const root=repo(),c=initial('R2','defect','medium','syn-backlog'),file=save(root,c),sealed=plan(root,c,file),set=verified(sealed,file,root);const unavailable=backlog.discover(root,{runner:()=>({status:1,stdout:'',stderr:'offline'})});expect(unavailable).toMatchObject({available:false,failure:true});expect(backlog.isTerminalLedgerStatus('Done')).toBe(true);expect(backlog.closesDeliveryOrRuntime({status:'Done'})).toBe(false);expect(()=>runtime.completeWork(file,{expectedRevision:set.state.revision,sourceRevision:set.state.source_revision,root})).toThrow(/complete requires delivery/);const delivery=runtime.advanceToDelivery(file,{expectedRevision:set.state.revision,sourceRevision:set.state.source_revision,root});expect(()=>runtime.recordRuntimeReceipt(file,{schema:'RuntimeReceipt/v2'},delivery.revision,delivery.source_revision)).toThrow(/delivery approval/);});

  test('nonblocking Runtime failure preserves a linked defect pointer and keeps the parent development-complete',()=>{const root=repo(),c=initial('R2','defect','medium','syn-runtime-failed'),file=save(root,c),sealed=plan(root,c,file),set=verified(sealed,file,root);let n=approved(set.state,file,root,'failed',false);expect(n.runtime_receipt).toMatchObject({status:'failed',blocking:false,gap_or_defect_pointer:'GAP-SYNTHETIC-001'});n=runtime.completeWork(file,{expectedRevision:n.revision,sourceRevision:n.source_revision,root});expect(n).toMatchObject({lifecycle_state:'COMPLETE',runtime_receipt:{status:'failed',blocking:false,gap_or_defect_pointer:'GAP-SYNTHETIC-001'}});});

  test('clarification, delivery feedback and blocking runtime failures fail closed without false transition claims',()=>{const root=repo(),c=initial('R2','defect','medium','syn-gates'),file=save(root,c);let n=runtime.beginTrace(file,{expectedRevision:1,sourceRevision:c.source_revision});const q={schema:'QuestionCandidate/v1',question_id:'Q-SYN-1',work_id:n.work_id,source_revision:n.source_revision,targets:['SR-QUALITY-1'],gap_class:'conflicting',action:'ask',type:'resolve_conflict',criticality:'blocking',blocking:true,decision_owner:'user',dependencies:[],context:'Two sources conflict.',why_asked:'The branch differs.',impact_if_unanswered:'Seal stays blocked.',text:'Which branch?',options:[{id:'A',label:'A',consequence:'Use A.',recommended:false},{id:'B',label:'B',consequence:'Use B.',recommended:false}],recommendation_rationale:null,allow_other:true,allow_cannot_answer:true,status:'open',answer:null};n=runtime.recordQuestionCandidate(file,q,n.revision,n.source_revision);n=runtime.recordHumanAnswer(file,{question_id:q.question_id,source_revision:n.source_revision,outcome:'cannot_answer',selected:[],quote:'Cannot decide.',pointer:'WORK.md#reply',answered_at:future()},n.revision,n.source_revision);const newSource='syn-gates-replanned';const replannedManifest={...n.acceptance_manifest,source_revision:newSource};expect(()=>runtime.replanWork(file,{expectedRevision:n.revision,sourceRevision:n.source_revision,newSourceRevision:newSource,sourcePlan:n.source_plan,acceptance:n.acceptance,testPlan:n.test_plan,acceptanceManifest:replannedManifest})).not.toThrow();n=JSON.parse(fs.readFileSync(file,'utf8'));expect(n.question_candidates).toEqual([]);expect(()=>runtime.recordHumanAnswer(file,{question_id:q.question_id,source_revision:newSource,outcome:'decision',selected:['A'],quote:'A.',pointer:'WORK.md#reply',answered_at:future()},n.revision,newSource)).toThrow(/unknown/);const delivery=initial('R2','defect','medium','syn-delivery-gap');delivery.lifecycle_state='DELIVERY';delivery.sealed_revision=1;delivery.sealed_at=future();delivery.implementation_fingerprint='a'.repeat(64);delivery.verification_completed_at=future();delivery.delivery_cycle_id='cycle';const approvedReceipt={schema:'DeliveryReceipt/v2',...binding(delivery),delivery_cycle_id:'cycle',decision:'approved',actor:'owner',source:'chat',timestamp:future(),sanitized_pointers:['WORK.md#approval']};delivery.delivery_receipt=approvedReceipt;const deliveryFile=save(root,delivery);for(const decision of ['feedback','rejected'])expect(()=>runtime.recordDeliveryReceipt(deliveryFile,{...approvedReceipt,decision},1,delivery.source_revision)).toThrow(/delivery receipt requires/);expect(()=>runtime.recordRuntimeReceipt(deliveryFile,{schema:'RuntimeReceipt/v2',...binding(delivery),status:'failed',blocking:true,environment:'test',actor:'owner',timestamp:future(),ac_refs:['AC-QUALITY-1'],sanitized_pointers:[],gap_or_defect_pointer:'DEF-SYN-1'},1,delivery.source_revision)).toThrow(/disposition invalid/);});

  test('stale CAS, stale import, expired lease and Static-as-Runtime evidence remain blocked',()=>{const root=repo(),c=initial('R2','defect','medium','syn-integrity'),file=save(root,c);expect(()=>runtime.beginTrace(file,{expectedRevision:2,sourceRevision:c.source_revision})).toThrow(/compare-and-swap/);const sealed=plan(root,c,file),set=verified(sealed,file,root);expect(()=>runtime.recordImportAttribution(file,{schema:'ImportAttribution/v1',...binding(set.state),import_id:'old',provider:'scenario',receipt_pointer:'imports/old',imported_at:'2000-01-01T00:00:00Z',status:'accepted'},set.state.revision,set.state.source_revision)).toThrow(/predates/);expect(()=>runtime.recordEvidence(file,evidence(set.state,'static-close','Static',{closes_runtime:true}),set.state.revision,set.state.source_revision)).toThrow(/cannot close Runtime/);expect(()=>runtime.validateContinuity({...set.state,leases:[{id:'expired',holder:'scenario',purpose:'test',status:'active',expires_at:'2000-01-01T00:00:00Z'}]},{expectedRevision:set.state.revision,sourceRevision:set.state.source_revision})).toThrow(/lease/);});
});

