'use strict';

const crypto=require('crypto');
const fs=require('fs');
const os=require('os');
const path=require('path');
const {execFileSync}=require('child_process');
const Ajv2020=require('ajv/dist/2020').default;
const runtime=require('../../lib/runtime.cjs');
const {checkpoint}=require('./fixtures.cjs');

function repo(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'runtime-architect-'));execFileSync('git',['init','-q'],{cwd:root});execFileSync('git',['config','user.email','architect@example.test'],{cwd:root});execFileSync('git',['config','user.name','architect'],{cwd:root});fs.writeFileSync(path.join(root,'scope.txt'),'scope');execFileSync('git',['add','.'],{cwd:root});execFileSync('git',['commit','-qm','base'],{cwd:root});return root;}
function save(root,c){const dir=path.join(root,'.agent','work',c.work_id);fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,'resume.json');fs.writeFileSync(file,JSON.stringify(c));return file;}
function binding(c){return {work_id:c.work_id,source_revision:c.source_revision,sealed_revision:c.sealed_revision,implementation_fingerprint:c.implementation_fingerprint,acceptance_manifest_id:c.acceptance_manifest.id,acceptance_manifest_version:c.acceptance_manifest.version};}
function stamp(){return new Date().toISOString();}
function packet(c,wave){return {schema:'BlindReviewPacket/v2',status:'frozen',packet_id:`packet-${wave}`,packet_version:1,wave,generation:wave,...binding(c),required_profile:{model:'configured',reasoning:'high'},review_scope:{paths:['scope.txt'],absence_assertions:{}},profile_attestation_set:'dispatch.json'};}
function dispatch(c,p){return {schema:'DispatchProfileAttestationSet/v1',...binding(c),packet_id:p.packet_id,packet_version:p.packet_version,wave:p.wave,orchestrator:'root',selector_source:'test',requested_model:'configured',requested_reasoning_effort:'high',runtime_metadata_observed:false,issued_at:stamp(),root_task_id:'root-task',root_dispatch_id:'root-dispatch',entries:runtime.lenses.map((lens,n)=>({task_id:`task-${n}`,dispatch_id:`dispatch-${n}`,reviewer_id:`reviewer-${n}`,lens,profile_verified:true,profile_verification:{verified_model:'configured',verified_reasoning_effort:'high',verification_source:'tests/profile',verification_pointer:`tests/profile-${n}`,verified_at:stamp()}}))};}
function review(c,p,kind){return {schema:'ReviewReceipt/v2',...binding(c),receipt_id:`receipt-${kind}`,reviewer_id:'reviewer-0',dispatch_task_id:'task-0',dispatch_id:'dispatch-0',lens:'correctness_regression',history_isolation:true,findings:['typed escalation'],finding_objects:[{finding_id:`finding-${kind}`,summary:'Requires independent architecture direction.',escalation:kind}],verdict:'changes_required',packet_id:p.packet_id,packet_version:p.packet_version,wave:p.wave};}
function decision(c,p,kind,extra={}){return {schema:'ArchitectDecision/v1',...binding(c),decision_id:`decision-${kind}`,review_generation:c.review_generation,packet_id:p.packet_id,packet_version:p.packet_version,wave:p.wave,trigger_receipt_ids:[`receipt-${kind}`],trigger_finding_ids:[`finding-${kind}`],scope:kind,architect_id:'architect-1',profile_verified:true,architect_profile:{model:'configured',reasoning:'high',verification_source:'tests/architect-profile',verification_pointer:'tests/architect-profile',verified_at:stamp()},implementer_id:'executor-1',decision:'Apply the smallest root-cause correction.',decision_pointer:'WORK.md#architect-decision',correction_pointer:'WORK.md#architect-correction',timestamp:stamp(),architect_not_reviewer_or_implementer:true,...extra};}
function architectDispatch(c,id='1'){return {schema:'ArchitectDiagnosticDispatch/v1',...binding(c),dispatch_id:`architect-dispatch-${id}`,task_id:`architect-task-${id}`,handle_id:`architect-handle-${id}`,architect_id:`architect-${id}`,requested_model:'gpt-5.6-sol',requested_reasoning_effort:'high',history_isolation:true,requirement_pointers:['BR:current-request','SR:observable-behavior',`AC:${c.acceptance_manifest.ac_ids[0]}`],external_observation_pointers:['observation:typed-finding'],forbidden_context_asserted:true,reserved_at:stamp()};}
function dispatchDigest(d){return crypto.createHash('sha256').update(runtime.stable({requirement_pointers:d.requirement_pointers,external_observation_pointers:d.external_observation_pointers,requested_model:d.requested_model,requested_reasoning_effort:d.requested_reasoning_effort,history_isolation:d.history_isolation,forbidden_context_asserted:d.forbidden_context_asserted})).digest('hex');}
function diagnosis(c,d,outcome='defect_found'){return {schema:'ArchitectureDiagnosis/v1',...binding(c),diagnosis_id:`diagnosis-${d.dispatch_id}`,dispatch_id:d.dispatch_id,task_id:d.task_id,handle_id:d.handle_id,architect_id:d.architect_id,history_isolation:true,blind_context_asserted:true,profile_verified:true,profile_verification:{verified_model:'gpt-5.6-sol',verified_reasoning_effort:'high',verification_source:'tests/architect-profile',verification_pointer:'tests/architect-profile',verified_at:stamp()},outcome,affected_ac_ids:c.acceptance_manifest.ac_ids,root_cause_hypothesis:'The externally observable behavior conflicts with the current acceptance contract.',correction_direction:'Correct the behavior without weakening the current acceptance contract.',dispatch_digest:dispatchDigest(d),timestamp:stamp()};}
function escalationState(kind,wave=kind==='persistent'?2:1){const root=repo(),base=checkpoint({work_id:`architect-${kind}-${wave}`,revision:1,lifecycle_state:'VERIFY',allowed_paths:['scope.txt'],fingerprint_paths:['scope.txt'],review_generation:wave}),p=packet(base,wave),c={...base,review_packet:p,review_generation_ledger:[{generation:wave,packet_id:p.packet_id,packet_version:p.packet_version,wave:p.wave}],dispatch_attestation_set:{packet_id:p.packet_id,packet_version:p.packet_version,wave:p.wave,pointer:'dispatch.json'}};const dir=path.join(root,'.agent','work',c.work_id);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'dispatch.json'),JSON.stringify(dispatch(c,p)));const file=save(root,c),next=runtime.recordReviewReceipt(file,review(c,p,kind),c.revision,c.source_revision,root);return {root,file,p,next};}

describe('ArchitectDecision/v1 escalation contract',()=>{
  test.each([['cross_scope',1],['persistent',2]])('a %s finding at wave %i blocks correction until a fresh independent architect decision exists',(kind,wave)=>{const {file,p,next}=escalationState(kind,wave);expect(runtime.architectEscalationRequired(next)).toBe(true);expect(()=>runtime.beginCorrection(file,{expectedRevision:next.revision,sourceRevision:next.source_revision,correction:{reason:'review finding',pointer:'WORK.md#correction'}})).toThrow(/architect decision/);const stored=runtime.recordArchitectDecision(file,decision(next,p,kind),next.revision,next.source_revision);expect(stored.architect_decision.decision_id).toBe(`decision-${kind}`);expect(()=>runtime.recordArchitectDecision(file,decision(stored,p,kind),stored.revision,stored.source_revision)).toThrow(/unassigned/);for(const correction of [{implementer_id:'architect-1',approved_by:'owner'},{implementer_id:'executor-2',approved_by:'owner'},{implementer_id:'executor-1',approved_by:'architect-1'}])expect(()=>runtime.beginCorrection(file,{expectedRevision:stored.revision,sourceRevision:stored.source_revision,correction:{reason:'architect direction',pointer:'WORK.md#correction',...correction}})).toThrow(/architect-separated/);expect(()=>runtime.beginCorrection(file,{expectedRevision:stored.revision,sourceRevision:stored.source_revision,correction:{reason:'architect direction',pointer:'WORK.md#correction',implementer_id:'',approved_by:'owner'}})).toThrow(/^architect correction implementer missing$/);expect(()=>runtime.beginCorrection(file,{expectedRevision:stored.revision,sourceRevision:stored.source_revision,correction:{reason:'architect direction',pointer:'WORK.md#correction',implementer_id:'executor-1',approved_by:''}})).toThrow(/^architect correction approver missing$/);const corrected=runtime.beginCorrection(file,{expectedRevision:stored.revision,sourceRevision:stored.source_revision,correction:{reason:'architect direction',pointer:'WORK.md#correction',implementer_id:'executor-1',approved_by:'owner'}});expect(corrected).toMatchObject({lifecycle_state:'EXECUTE',architect_decision:null,reviews:[],review_packet:null});});

  test('first-wave persistent and legacy string findings remain compatible without an architect gate',()=>{const {file,p,next}=escalationState('persistent',1);expect(runtime.architectEscalationRequired(next)).toBe(false);expect(()=>runtime.recordArchitectDecision(file,decision(next,p,'persistent'),next.revision,next.source_revision)).toThrow(/not required/);expect(runtime.beginCorrection(file,{expectedRevision:next.revision,sourceRevision:next.source_revision,correction:{reason:'ordinary finding',pointer:'WORK.md#correction'}}).lifecycle_state).toBe('EXECUTE');});

  test.each([['cross_scope',1],['persistent',2]])('%s escalation at streak zero supports blind diagnosis before correction without a deadlock',(kind,wave)=>{const {file,next}=escalationState(kind,wave);expect(next.review_failure_streak||0).toBe(0);expect(runtime.architectDiagnosticRequired(next)).toBe(true);expect(next.next_action).toMatch(/Reserve one fresh history-isolated blind architect/);const d=architectDispatch(next,`${kind}-first`),assigned=runtime.recordArchitectDiagnosticDispatch(file,d,next.revision,next.source_revision);expect(assigned.architect_diagnostic_dispatch).toMatchObject({dispatch_id:d.dispatch_id,architect_id:d.architect_id});const diagnosed=runtime.recordArchitectureDiagnosis(file,diagnosis(assigned,d),assigned.revision,assigned.source_revision);expect(diagnosed.architect_decision).toBeUndefined();expect(diagnosed.architecture_diagnosis).toMatchObject({outcome:'defect_found',dispatch_id:d.dispatch_id});const corrected=runtime.beginCorrection(file,{expectedRevision:diagnosed.revision,sourceRevision:diagnosed.source_revision,correction:{reason:'architect direction',pointer:'WORK.md#architect-correction',implementer_id:'executor-1',approved_by:'owner'}});expect(corrected).toMatchObject({lifecycle_state:'EXECUTE',architect_decision:null,review_failure_streak:0,architecture_diagnosis:null});});

  test('no-defect diagnosis retires the reviewed packet and opens the next fresh review boundary',()=>{const {file,next}=escalationState('persistent',2),d=architectDispatch(next,'no-defect-current'),assigned=runtime.recordArchitectDiagnosticDispatch(file,d,next.revision,next.source_revision),diagnosed=runtime.recordArchitectureDiagnosis(file,diagnosis(assigned,d,'no_architectural_defect_found'),assigned.revision,assigned.source_revision);expect(diagnosed).toMatchObject({lifecycle_state:'VERIFY',review_packet:null,reviews:[],verification:[],review_failure_streak:0,architecture_diagnosis:null});expect(diagnosed.architecture_diagnosis_history).toHaveLength(1);const fresh=runtime.freezeReviewPacket(file,packet(diagnosed,diagnosed.review_generation+1),diagnosed.revision,diagnosed.source_revision);expect(fresh.review_generation).toBe(next.review_generation+1);});

  test('typed decisions reject replay, stale bindings, unsafe pointers, profile, trigger, reviewer and implementer alternatives',()=>{const {root,file,p,next}=escalationState('cross_scope');const base=decision(next,p,'cross_scope');for(const bad of [{...base,source_revision:'stale'},{...base,packet_id:'other-packet'},{...base,architect_id:'reviewer-0'},{...base,implementer_id:'architect-1'},{...base,profile_verified:false},{...base,architect_profile:null},{...base,architect_profile:{...base.architect_profile,verification_pointer:'Bearer secret'}},{...base,trigger_receipt_ids:['missing']},{...base,trigger_finding_ids:['missing']},{...base,scope:'persistent'},{...base,timestamp:'2000-01-01T00:00:00Z'}])expect(()=>runtime.recordArchitectDecision(file,bad,next.revision,next.source_revision)).toThrow();const wrongState={...next,lifecycle_state:'DELIVERY'},wrongFile=save(root,wrongState);expect(()=>runtime.recordArchitectDecision(wrongFile,base,next.revision,next.source_revision)).toThrow(/^architect decision requires unassigned verify escalation$/);fs.writeFileSync(file,JSON.stringify(next));const nonCross={...next,reviews:[{...next.reviews[0],finding_objects:[{...next.reviews[0].finding_objects[0],escalation:'persistent'}]}]};expect(()=>runtime.validateArchitectDecision(base,nonCross)).toThrow(/cross-scope trigger/);for(const finding_objects of [[null],{}]){const typedReview={...review(next,p,'cross_scope'),finding_objects};expect(()=>runtime.recordReviewReceipt(file,typedReview,next.revision,next.source_revision,root)).toThrow(/review receipt binding/);}expect(JSON.parse(fs.readFileSync(file,'utf8')).architect_decision).toBeUndefined();});

  test.each([['cross_scope',1],['persistent',2]])('direct architect validator preserves every %s decision binding at wave %i',(kind,wave)=>{
    const {p,next}=escalationState(kind,wave),base=decision(next,p,kind);
    expect(runtime.validateArchitectDecision(base,next)).toEqual(base);
    for(const [field,message] of [['decision_id','architect decision id missing'],['architect_id','architect id missing'],['implementer_id','architect implementer missing'],['decision','architect decision missing'],['decision_pointer','architect decision pointer missing'],['correction_pointer','architect correction pointer missing'],['timestamp','architect timestamp missing']])expect(()=>runtime.validateArchitectDecision({...base,[field]:''},next)).toThrow(message);
    for(const [field,message] of [['model','architect model missing'],['reasoning','architect reasoning missing'],['verification_source','architect profile source missing'],['verification_pointer','architect profile pointer missing'],['verified_at','architect profile timestamp missing']])expect(()=>runtime.validateArchitectDecision({...base,architect_profile:{...base.architect_profile,[field]:''}},next)).toThrow(message);
    for(const bad of [{...base,schema:'ArchitectDecision/v0'},{...base,scope:'other'},{...base,profile_verified:false},{...base,architect_not_reviewer_or_implementer:false},{...base,trigger_receipt_ids:[]},{...base,trigger_finding_ids:[]},{...base,trigger_receipt_ids:[base.trigger_receipt_ids[0],base.trigger_receipt_ids[0]]},{...base,trigger_finding_ids:[base.trigger_finding_ids[0],base.trigger_finding_ids[0]]}])expect(()=>runtime.validateArchitectDecision(bad,next)).toThrow(/architect decision invalid/);
    for(const field of ['review_generation','packet_id','packet_version','wave'])expect(()=>runtime.validateArchitectDecision({...base,[field]:typeof base[field]==='number'?base[field]+1:'other'},next)).toThrow(/architect decision packet binding/);
    expect(()=>runtime.validateArchitectDecision({...base,architect_profile:{...base.architect_profile,verification_source:'Bearer secret'}},next)).toThrow(/sanitized pointer invalid/);
    expect(()=>runtime.validateArchitectDecision({...base,architect_profile:{...base.architect_profile,verified_at:'2000-01-01T00:00:00Z'}},next)).toThrow(/architect profile timestamp/);
  });

  test('architect escalation is existential, null-safe and tied to attributable typed triggers',()=>{
    const cross=escalationState('cross_scope',1),persistent=escalationState('persistent',2);
    for(const state of [cross.next,persistent.next]){
      const ordinary={...state.reviews[0],finding_objects:[]};
      expect(runtime.architectEscalationRequired({...state,reviews:[state.reviews[0],ordinary]})).toBe(true);
      expect(runtime.architectEscalationRequired({...state,reviews:[ordinary]})).toBe(false);
      expect(runtime.architectEscalationRequired({...state,reviews:[{...ordinary,finding_objects:undefined}]})).toBe(false);
      expect(runtime.architectEscalationRequired({...state,reviews:[{...ordinary,finding_objects:[null]}]})).toBe(false);
      expect(runtime.architectEscalationRequired({...state,reviews:[null]})).toBe(false);
      expect(runtime.architectEscalationRequired({...state,reviews:undefined})).toBe(false);
    }
    const base=decision(cross.next,cross.p,'cross_scope');
    expect(()=>runtime.validateArchitectDecision({...base,architect_profile:null},cross.next)).toThrow(/architect decision invalid/);
    expect(()=>runtime.validateArchitectDecision({...base,source_revision:'stale'},cross.next)).toThrow(/architect decision binding invalid/);
    expect(()=>runtime.validateArchitectDecision({...base,packet_id:'stale-packet'},cross.next)).toThrow(/architect decision packet binding invalid/);
    expect(()=>runtime.validateArchitectDecision({...base,timestamp:'2000-01-01T00:00:00Z'},cross.next)).toThrow(/architect decision timestamp/);
    expect(()=>runtime.validateArchitectDecision(base,{...cross.next,reviews:undefined})).toThrow(/architect trigger receipt missing/);
    expect(()=>runtime.validateArchitectDecision({...base,trigger_receipt_ids:['missing']},cross.next)).toThrow(/architect trigger receipt missing/);
    expect(()=>runtime.validateArchitectDecision({...base,trigger_finding_ids:['missing']},cross.next)).toThrow(/architect trigger finding missing/);
    const wrongCross={...cross.next,reviews:[{...cross.next.reviews[0],finding_objects:[{...cross.next.reviews[0].finding_objects[0],escalation:'persistent'}]}]};
    expect(()=>runtime.validateArchitectDecision(base,wrongCross)).toThrow(/architect cross-scope trigger missing/);
    const persistentBase=decision(persistent.next,persistent.p,'persistent'),wrongPersistent={...persistent.next,reviews:[{...persistent.next.reviews[0],finding_objects:[{...persistent.next.reviews[0].finding_objects[0],escalation:'cross_scope'}]}]};
    expect(()=>runtime.validateArchitectDecision(persistentBase,wrongPersistent)).toThrow(/architect persistent trigger missing/);
    const persistentOrdinary={...persistent.next.reviews[0],receipt_id:'receipt-persistent-ordinary',reviewer_id:'reviewer-persistent-ordinary',finding_objects:[{finding_id:'finding-persistent-ordinary',summary:'A different escalation.',escalation:'cross_scope'}]},persistentLinked={...persistentBase,trigger_receipt_ids:['receipt-persistent','receipt-persistent-ordinary'],trigger_finding_ids:['finding-persistent','finding-persistent-ordinary']};
    expect(runtime.validateArchitectDecision(persistentLinked,{...persistent.next,reviews:[persistent.next.reviews[0],persistentOrdinary]})).toEqual(persistentLinked);
  });

  test('architect trigger sets retain every receipt/finding and checkpoint validation invokes the stored decision',()=>{
    const {p,next}=escalationState('cross_scope',1),ordinary={...next.reviews[0],receipt_id:'receipt-ordinary',reviewer_id:'reviewer-ordinary',finding_objects:[{finding_id:'finding-ordinary',summary:'Ordinary correction.',escalation:'persistent'}]},state={...next,reviews:[next.reviews[0],ordinary]},base=decision(state,p,'cross_scope');
    const linked={...base,trigger_receipt_ids:['receipt-cross_scope','receipt-ordinary'],trigger_finding_ids:['finding-cross_scope','finding-ordinary']};
    expect(runtime.validateArchitectDecision(linked,state)).toEqual(linked);
    expect(()=>runtime.validateArchitectDecision({...linked,trigger_receipt_ids:['receipt-cross_scope','missing']},state)).toThrow(/architect trigger receipt missing/);
    expect(()=>runtime.validateArchitectDecision({...linked,trigger_finding_ids:['finding-cross_scope','missing']},state)).toThrow(/architect trigger finding missing/);
    expect(()=>runtime.validateArchitectDecision({...base,architect_id:'reviewer-0'},next)).toThrow(/architect independence invalid/);
    for(const [field,message] of [['decision_pointer','sanitized pointer invalid'],['correction_pointer','sanitized pointer invalid']])expect(()=>runtime.validateArchitectDecision({...base,[field]:'secret=value'},next)).toThrow(message);
    expect(runtime.assertCheckpoint({...next,architect_decision:base})).toBe(true);
    expect(()=>runtime.assertCheckpoint({...next,architect_decision:{...base,architect_id:'reviewer-0'}})).toThrow(/architect independence invalid/);
  });

  test('schema accepts the canonical decision and rejects an omitted independence binding',()=>{const {p,next}=escalationState('cross_scope');const value=decision(next,p,'cross_scope');const schema=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../../schemas/architect-decision.v1.schema.json'),'utf8'));const validate=new Ajv2020({strict:false,validateFormats:false}).compile(schema);expect(validate(value),JSON.stringify(validate.errors)).toBe(true);const invalid={...value,architect_not_reviewer_or_implementer:false};expect(validate(invalid)).toBe(false);});
});
