'use strict';
const fs=require('fs'),os=require('os'),path=require('path');
const {execFileSync}=require('child_process');
const runtime=require('../../lib/runtime.cjs');
const {checkpoint}=require('./fixtures.cjs');
function repo(){const r=fs.mkdtempSync(path.join(os.tmpdir(),'runtime-coordination-'));execFileSync('git',['init','-q'],{cwd:r});execFileSync('git',['config','user.email','test@local'],{cwd:r});execFileSync('git',['config','user.name','test'],{cwd:r});fs.mkdirSync(path.join(r,'src'));fs.writeFileSync(path.join(r,'src','a.js'),'a');fs.writeFileSync(path.join(r,'src','b.js'),'b');execFileSync('git',['add','.'],{cwd:r});execFileSync('git',['commit','-qm','base'],{cwd:r});return r;}
function save(r,c){const d=path.join(r,'.agent','work',c.work_id);fs.mkdirSync(d,{recursive:true});const f=path.join(d,'resume.json');fs.writeFileSync(f,JSON.stringify(c));return f;}
function plan(work){const c=checkpoint({work_id:work,revision:1,lifecycle_state:'PLAN',protocol_version:'agent-development-runtime/v2',allowed_paths:['src/a.js','src/b.js'],fingerprint_paths:['src/a.js','src/b.js'],sealed_at:undefined,sealed_revision:undefined,implementation_fingerprint:undefined});return c;}
function scope(c){return {work_id:c.work_id,thread_id:`thread-${c.work_id}`,source_revision:c.source_revision,contour_keys:['br:BR-1','file:src/a.js','file:src/b.js'],exclusive_resources:['file:src/a.js','file:src/b.js']};}
describe('v3 checkpoint coordination adapter',()=>{
 test('v2 remains valid while v3 fails closed without closed binding',()=>{expect(()=>runtime.assertCheckpoint(checkpoint())).not.toThrow();expect(()=>runtime.assertCheckpoint({...checkpoint(),protocol_version:'agent-development-runtime/v3'})).toThrow(/v3 coordination/);});
 test('v3 authorizes active subset, survives refresh and blocks seal until full scope',()=>{const r=repo(),owner=plan('owner'),mixed=plan('mixed'),ownerFile=save(r,owner),mixedFile=save(r,mixed);let o=runtime.registerCoordinationScope(ownerFile,{expectedRevision:1,sourceRevision:owner.source_revision,root:r,scope:scope(owner)});o=runtime.claimCoordinationResources(ownerFile,{expectedRevision:o.revision,sourceRevision:o.source_revision,root:r,resources:['file:src/a.js'],lease_expires_at:new Date(Date.now()+60000).toISOString()});let m=runtime.registerCoordinationScope(mixedFile,{expectedRevision:1,sourceRevision:mixed.source_revision,root:r,scope:scope(mixed)});m=runtime.claimCoordinationResources(mixedFile,{expectedRevision:m.revision,sourceRevision:m.source_revision,root:r,resources:['file:src/b.js'],lease_expires_at:new Date(Date.now()+60000).toISOString()});expect(()=>runtime.validateMutationResources(m,{root:r,resources:['file:src/b.js']})).not.toThrow();expect(()=>runtime.validateMutationResources(m,{root:r,resources:['file:src/a.js']})).toThrow(/claim/);m=runtime.refreshCoordination(mixedFile,{expectedRevision:m.revision,sourceRevision:m.source_revision,root:r});m={...m,lifecycle_state:'EXECUTE'};fs.writeFileSync(mixedFile,JSON.stringify(m));expect(()=>runtime.sealMutation(mixedFile,m.revision,m.source_revision,r)).toThrow(/blocked|active resources|claim/);expect(o.coordination.active_resources).toContain('file:src/a.js');});
 test('v3 rejects malformed binding and reaches ready only after full handoff resolution',()=>{
  const r=repo(),owner=plan('owner'),mixed=plan('mixed'),ownerFile=save(r,owner),mixedFile=save(r,mixed),ownerScope={...scope(owner),contour_keys:['br:BR-1','file:src/a.js'],exclusive_resources:['file:src/a.js']};
  expect(()=>runtime.registerCoordinationScope(ownerFile,{expectedRevision:1,sourceRevision:owner.source_revision,root:r,scope:{...ownerScope,thread_id:''}})).toThrow(/thread/);
  let o=runtime.registerCoordinationScope(ownerFile,{expectedRevision:1,sourceRevision:owner.source_revision,root:r,scope:ownerScope});
  o=runtime.claimCoordinationResources(ownerFile,{expectedRevision:o.revision,sourceRevision:o.source_revision,root:r,resources:['file:src/a.js'],lease_expires_at:new Date(Date.now()+60000).toISOString()});
  let m=runtime.registerCoordinationScope(mixedFile,{expectedRevision:1,sourceRevision:mixed.source_revision,root:r,scope:scope(mixed)});
  m=runtime.claimCoordinationResources(mixedFile,{expectedRevision:m.revision,sourceRevision:m.source_revision,root:r,resources:['file:src/b.js'],lease_expires_at:new Date(Date.now()+60000).toISOString()});
  o={...o,lifecycle_state:'EXECUTE'};fs.writeFileSync(ownerFile,JSON.stringify(o));
  runtime.readyForHandoff(ownerFile,{expectedRevision:o.revision,sourceRevision:o.source_revision,root:r});
  const n=runtime.coordination.status(r).notices.find(x=>x.contender_work_id==='mixed');runtime.coordination.disposition(r,{notice_id:n.notice_id,kind:'handoff',decided_by:'root',decision_pointer:'WORK.md#handoff'});
  m=runtime.claimCoordinationResources(mixedFile,{expectedRevision:m.revision,sourceRevision:m.source_revision,root:r,resources:['file:src/a.js'],lease_expires_at:new Date(Date.now()+60000).toISOString()});
  m={...m,lifecycle_state:'EXECUTE'};fs.writeFileSync(mixedFile,JSON.stringify(m));m=runtime.readyForHandoff(mixedFile,{expectedRevision:m.revision,sourceRevision:m.source_revision,root:r});expect(m.handoff_state).toBe('READY_FOR_HANDOFF');
 });
 test('v3 adapter fails closed for missing claims, stale binding and invalid stage operations',()=>{const r=repo(),base=plan('fault'),file=save(r,base),r0={...plan('r0'),route:'R0'},r0File=save(r,r0);expect(()=>runtime.registerCoordinationScope(r0File,{expectedRevision:1,sourceRevision:r0.source_revision,root:r,scope:scope(r0)})).toThrow(/read-only/);let c=runtime.registerCoordinationScope(file,{expectedRevision:1,sourceRevision:base.source_revision,root:r,scope:scope(base)});expect(()=>runtime.validateCoordination(c,r)).toThrow(/active resources/);expect(()=>runtime.validateMutationResources(c,{root:r,resources:[]})).toThrow(/resources/);expect(()=>runtime.claimCoordinationResources(file,{expectedRevision:c.revision,sourceRevision:c.source_revision,root:r,resources:['file:src/a.js']})).toThrow(/lease/);c={...c,lifecycle_state:'TRACE'};fs.writeFileSync(file,JSON.stringify(c));expect(()=>runtime.claimCoordinationResources(file,{expectedRevision:c.revision,sourceRevision:c.source_revision,root:r,resources:['file:src/a.js'],lease_expires_at:new Date(Date.now()+60000).toISOString()})).toThrow(/plan\/execute/);expect(()=>runtime.recoverCoordinationClaim(file,{expectedRevision:c.revision,sourceRevision:c.source_revision,root:r,resources:['file:src/a.js'],decidedBy:'operator',decisionPointer:'WORK.md#recover'})).toThrow(/plan\/execute/);expect(()=>runtime.readyForHandoff(file,{expectedRevision:c.revision,sourceRevision:c.source_revision,root:r})).toThrow(/execute/);c={...c,lifecycle_state:'PLAN'};fs.writeFileSync(file,JSON.stringify(c));expect(()=>runtime.registerCoordinationScope(file,{expectedRevision:c.revision,sourceRevision:c.source_revision,root:r,scope:scope(c)})).toThrow(/unbound/);const ledger=path.join(r,'.agent','coordination','ownership.v1.json'),state=JSON.parse(fs.readFileSync(ledger,'utf8'));state.tickets=[];fs.writeFileSync(ledger,JSON.stringify(state));expect(()=>runtime.refreshCoordination(file,{expectedRevision:c.revision,sourceRevision:c.source_revision,root:r})).toThrow(/ticket missing/);});
 test('v3 retires expired same-ticket claims before a fresh claim can seal',()=>{const r=repo(),base=plan('reclaim'),file=save(r,base),future=new Date(Date.now()+60000).toISOString();let c=runtime.registerCoordinationScope(file,{expectedRevision:1,sourceRevision:base.source_revision,root:r,scope:scope(base)});c=runtime.claimCoordinationResources(file,{expectedRevision:c.revision,sourceRevision:c.source_revision,root:r,resources:['file:src/a.js','file:src/b.js'],lease_expires_at:future});const ledgerFile=path.join(r,'.agent','coordination','ownership.v1.json'),expire=()=>{const state=JSON.parse(fs.readFileSync(ledgerFile,'utf8'));for(const claim of state.claims.filter(x=>x.status==='active'))claim.lease_expires_at='2000-01-01T00:00:00Z';fs.writeFileSync(ledgerFile,JSON.stringify(state));};expire();c=runtime.recoverCoordinationClaim(file,{expectedRevision:c.revision,sourceRevision:c.source_revision,root:r,resources:['file:src/a.js','file:src/b.js'],decidedBy:'operator',decisionPointer:'WORK.md#claim-recovery'});expect(c.coordination.active_resources).toEqual([]);c=runtime.claimCoordinationResources(file,{expectedRevision:c.revision,sourceRevision:c.source_revision,root:r,resources:['file:src/a.js','file:src/b.js'],lease_expires_at:future});expire();c=runtime.claimCoordinationResources(file,{expectedRevision:c.revision,sourceRevision:c.source_revision,root:r,resources:['file:src/a.js','file:src/b.js'],lease_expires_at:future});expect(()=>runtime.validateCoordination(c,r,true)).not.toThrow();c={...c,lifecycle_state:'EXECUTE'};fs.writeFileSync(file,JSON.stringify(c));const sealed=runtime.sealMutation(file,c.revision,c.source_revision,r);expect(sealed.lifecycle_state).toBe('VERIFY');const claims=runtime.coordination.read(ledgerFile).claims;expect(claims.filter(x=>x.status==='recovered').length).toBeGreaterThanOrEqual(2);expect(claims.filter(x=>x.status==='active')).toHaveLength(1);});
 test('v3 scope rejects a mismatched binding and full validation rejects a queued resource',()=>{
  const r=repo(),owner=plan('block-owner'),waiter=plan('block-waiter'),ownerFile=save(r,owner),waiterFile=save(r,waiter);
  expect(()=>runtime.registerCoordinationScope(ownerFile,{expectedRevision:1,sourceRevision:owner.source_revision,root:r,scope:{...scope(owner),work_id:'wrong'}})).toThrow(/scope/);
  let o=runtime.registerCoordinationScope(ownerFile,{expectedRevision:1,sourceRevision:owner.source_revision,root:r,scope:{...scope(owner),contour_keys:['file:src/a.js'],exclusive_resources:['file:src/a.js']}});
  runtime.claimCoordinationResources(ownerFile,{expectedRevision:o.revision,sourceRevision:o.source_revision,root:r,resources:['file:src/a.js'],lease_expires_at:new Date(Date.now()+60000).toISOString()});
  let w=runtime.registerCoordinationScope(waiterFile,{expectedRevision:1,sourceRevision:waiter.source_revision,root:r,scope:scope(waiter)});
  w=runtime.claimCoordinationResources(waiterFile,{expectedRevision:w.revision,sourceRevision:w.source_revision,root:r,resources:['file:src/a.js','file:src/b.js'],lease_expires_at:new Date(Date.now()+60000).toISOString()});
  expect(w.coordination.active_resources).toEqual(['file:src/b.js']);expect(w.coordination.blocked_resources).toEqual(['file:src/a.js']);expect(runtime.validateCoordination(w,r)).toBe(true);expect(()=>runtime.validateCoordination(w,r,true)).toThrow(/blocked/);
 });
 test('v3 binding shape, full/default resource selection and continuity root are independently observable',()=>{
  const r=repo(),base=plan('exact-binding'),file=save(r,base);let c=runtime.registerCoordinationScope(file,{expectedRevision:1,sourceRevision:base.source_revision,root:r,scope:scope(base)});c=runtime.claimCoordinationResources(file,{expectedRevision:c.revision,sourceRevision:c.source_revision,root:r,resources:['file:src/a.js','file:src/b.js'],lease_expires_at:new Date(Date.now()+60000).toISOString()});
  expect(runtime.validateCoordination(c,r)).toBe(true);expect(runtime.validateCoordination(c,r,true)).toBe(true);expect(runtime.validateContinuity(c,{expectedRevision:c.revision,sourceRevision:c.source_revision,root:r})).toBe(true);
  for(const [input,error] of [[{expectedRevision:'3',sourceRevision:c.source_revision},/expected revision/],[{expectedRevision:c.revision+1,sourceRevision:c.source_revision},/expected revision/],[{expectedRevision:c.revision,sourceRevision:''},/source revision/],[{expectedRevision:c.revision,sourceRevision:'wrong'},/source revision/]])expect(()=>runtime.validateContinuity(c,{...input,root:r})).toThrow(error);
  const valid=c.coordination;for(const [coordination,error] of [[null,/binding/],[{...valid,schema:'Wrong/v1'},/binding/],[{...valid,work_id:'wrong'},/binding/],[{...valid,generation:'1'},/binding/],[{...valid,generation:0},/binding/],[{...valid,exclusive_resources:null},/binding/],[{...valid,active_resources:null},/binding/],[{...valid,blocked_resources:null},/binding/],[{...valid,exclusive_resources:[]},/binding/],[{...valid,thread_id:''},/^coordination thread missing$/],[{...valid,ticket_id:''},/^coordination ticket missing$/]])expect(()=>runtime.assertCheckpoint({...c,coordination})).toThrow(error);
 });
 test('typed rebind expands an existing ticket and recovers an expired overlapping claim before a fresh claim',()=>{
  const r=repo(),foreign=plan('foreign-owner'),target=plan('rebind-target'),foreignFile=save(r,foreign),targetFile=save(r,target),future=new Date(Date.now()+60000).toISOString();
  let owner=runtime.registerCoordinationScope(foreignFile,{expectedRevision:1,sourceRevision:foreign.source_revision,root:r,scope:{...scope(foreign),contour_keys:['br:BR-1','file:src/a.js'],exclusive_resources:['file:src/a.js']}});
  owner=runtime.claimCoordinationResources(foreignFile,{expectedRevision:owner.revision,sourceRevision:owner.source_revision,root:r,resources:['file:src/a.js'],lease_expires_at:future});
  let current=runtime.registerCoordinationScope(targetFile,{expectedRevision:1,sourceRevision:target.source_revision,root:r,scope:{...scope(target),contour_keys:['br:BR-1','file:src/b.js'],exclusive_resources:['file:src/b.js']}});
  current=runtime.claimCoordinationResources(targetFile,{expectedRevision:current.revision,sourceRevision:current.source_revision,root:r,resources:['file:src/b.js'],lease_expires_at:future});
  const ledgerFile=path.join(r,'.agent','coordination','ownership.v1.json');const ledger=JSON.parse(fs.readFileSync(ledgerFile,'utf8'));for(const claim of ledger.claims.filter(x=>x.ticket_id===owner.coordination.ticket_id))claim.lease_expires_at='2000-01-01T00:00:00Z';const targetTicket=ledger.tickets.find(x=>x.ticket_id===current.coordination.ticket_id);targetTicket.source_revision='git:historical-before-current-scope';expect(targetTicket.source_revision).toBe('git:historical-before-current-scope');fs.writeFileSync(ledgerFile,JSON.stringify(ledger));
  const expanded=runtime.rebindCoordinationScope(targetFile,{expectedRevision:current.revision,sourceRevision:current.source_revision,root:r,expectedLedgerRevision:runtime.coordination.status(r).ledger_revision,ticket_id:current.coordination.ticket_id,scope:{schema:'CoordinationScope/v1',work_id:current.work_id,thread_id:current.coordination.thread_id,source_revision:current.source_revision,contour_keys:['br:BR-1','file:src/a.js','file:src/b.js'],exclusive_resources:['file:src/a.js','file:src/b.js']},lease_expires_at:future,actor:'runtime:test',decision_pointer:'WORK.md#coordination-rebind',reason:'Expand the accepted correction contour.'});
  expect(expanded.coordination.exclusive_resources).toEqual(['file:src/a.js','file:src/b.js']);expect(expanded.coordination.active_resources).toEqual(['file:src/b.js']);expect(expanded.coordination_rebind_history[0].retired_claim_ids).toHaveLength(1);expect(expanded.coordination_rebind_history[0].previous_source_revision).toBe('git:historical-before-current-scope');
  const claimed=runtime.claimCoordinationResources(targetFile,{expectedRevision:expanded.revision,sourceRevision:expanded.source_revision,root:r,resources:['file:src/a.js'],lease_expires_at:future});expect(claimed.coordination.active_resources).toEqual(['file:src/a.js','file:src/b.js']);expect(runtime.validateCoordination(claimed,r,true)).toBe(true);
 });
 test('typed rebind creates a current ticket for a stale binding and rejects live overlap atomically',()=>{
  const r=repo(),foreign=plan('foreign-live'),foreignFile=save(r,foreign),future=new Date(Date.now()+60000).toISOString();let owner=runtime.registerCoordinationScope(foreignFile,{expectedRevision:1,sourceRevision:foreign.source_revision,root:r,scope:{...scope(foreign),contour_keys:['br:BR-1','file:src/a.js'],exclusive_resources:['file:src/a.js']}});owner=runtime.claimCoordinationResources(foreignFile,{expectedRevision:owner.revision,sourceRevision:owner.source_revision,root:r,resources:['file:src/a.js'],lease_expires_at:future});
  const stale=plan('stale-rebind'),staleState={...stale,protocol_version:'agent-development-runtime/v3',review_dispatch_reservation_ledger:[],coordination:{schema:'CoordinationBinding/v1',work_id:stale.work_id,thread_id:'old-thread',ticket_id:'missing-ticket',generation:1,exclusive_resources:['file:src/a.js'],active_resources:[],blocked_resources:[]}},staleFile=save(r,staleState),beforeCheckpoint=fs.readFileSync(staleFile,'utf8'),beforeLedger=fs.readFileSync(path.join(r,'.agent','coordination','ownership.v1.json'),'utf8');
  expect(()=>runtime.rebindCoordinationScope(staleFile,{expectedRevision:1,sourceRevision:stale.source_revision,root:r,expectedLedgerRevision:runtime.coordination.status(r).ledger_revision-1,ticket_id:'ticket-stale-current',scope:{schema:'CoordinationScope/v1',work_id:stale.work_id,thread_id:'new-thread',source_revision:stale.source_revision,contour_keys:['br:BR-1','file:src/a.js'],exclusive_resources:['file:src/a.js']},lease_expires_at:future,actor:'runtime:test',decision_pointer:'WORK.md#coordination-rebind',reason:'Rebind a missing legacy ticket.'})).toThrow(/compare-and-swap/);
  expect(()=>runtime.rebindCoordinationScope(staleFile,{expectedRevision:1,sourceRevision:stale.source_revision,root:r,expectedLedgerRevision:runtime.coordination.status(r).ledger_revision,ticket_id:'ticket-stale-current',scope:{schema:'CoordinationScope/v1',work_id:stale.work_id,thread_id:'new-thread',source_revision:stale.source_revision,contour_keys:['br:BR-1','file:src/a.js'],exclusive_resources:['file:src/a.js']},lease_expires_at:future,actor:'runtime:test',decision_pointer:'WORK.md#coordination-rebind',reason:'Rebind a missing legacy ticket.'})).toThrow(/live ticket/);
  expect(fs.readFileSync(staleFile,'utf8')).toBe(beforeCheckpoint);expect(fs.readFileSync(path.join(r,'.agent','coordination','ownership.v1.json'),'utf8')).toBe(beforeLedger);
  const expiredLedger=JSON.parse(beforeLedger);for(const claim of expiredLedger.claims.filter(x=>x.ticket_id===owner.coordination.ticket_id))claim.lease_expires_at='2000-01-01T00:00:00Z';fs.writeFileSync(path.join(r,'.agent','coordination','ownership.v1.json'),JSON.stringify(expiredLedger));
  const rebound=runtime.rebindCoordinationScope(staleFile,{expectedRevision:1,sourceRevision:stale.source_revision,root:r,expectedLedgerRevision:runtime.coordination.status(r).ledger_revision,ticket_id:'ticket-stale-current',scope:{schema:'CoordinationScope/v1',work_id:stale.work_id,thread_id:'new-thread',source_revision:stale.source_revision,contour_keys:['br:BR-1','file:src/a.js'],exclusive_resources:['file:src/a.js']},lease_expires_at:future,actor:'runtime:test',decision_pointer:'WORK.md#coordination-rebind',reason:'Rebind a missing legacy ticket.'});expect(rebound.coordination.ticket_id).toBe('ticket-stale-current');expect(rebound.coordination.active_resources).toEqual([]);expect(rebound.coordination_rebind_history[0].previous_ticket_id).toBe('missing-ticket');
  const claimed=runtime.claimCoordinationResources(staleFile,{expectedRevision:rebound.revision,sourceRevision:rebound.source_revision,root:r,resources:['file:src/a.js'],lease_expires_at:future});expect(claimed.coordination.active_resources).toEqual(['file:src/a.js']);expect(runtime.validateCoordination(claimed,r,true)).toBe(true);
 });
});
