'use strict';
const fs=require('fs'),os=require('os'),path=require('path');
const c=require('../../lib/workstream-coordination.cjs');
function root(){return fs.mkdtempSync(path.join(os.tmpdir(),'coordination-'));}
function scope(work,file,extra={}){return {work_id:work,thread_id:`thread-${work}`,source_revision:'live-v1',contour_keys:['br:BR-1','sr:SR-1',`component:${extra.component||'Case'}`,`file:${file}`],exclusive_resources:[`file:${file}`]};}
function enqueue(r,work,file,extra){return c.enqueue(r,scope(work,file,extra));}
function lease(){return new Date(Date.now()+60000).toISOString();}
describe('shared worktree coordination',()=>{
 test('same file is FIFO, visible by work/thread and cannot be stolen',()=>{const r=root();enqueue(r,'first','src/a.js');enqueue(r,'second','src/a.js');let s=c.status(r);expect(s.notices).toHaveLength(1);expect(s.notices[0].owner_work_id).toBe('first');expect(s.notices[0].owner_thread_id).toBe('thread-first');c.acknowledge(r,{notice_id:s.notices[0].notice_id,actor:'thread-second'});c.acknowledge(r,{notice_id:s.notices[0].notice_id,actor:'thread-second'});s=c.status(r);expect(s.notices[0]).toMatchObject({status:'acknowledged',acknowledgements:[{actor:'thread-second',at:expect.any(String)}]});const a=s.tickets.find(x=>x.work_id==='first'),b=s.tickets.find(x=>x.work_id==='second');c.requestClaim(r,{ticket_id:a.ticket_id,lease_expires_at:lease()});expect(()=>c.requestClaim(r,{ticket_id:b.ticket_id,lease_expires_at:lease()})).toThrow(/FIFO/);c.ready(r,{ticket_id:a.ticket_id});c.disposition(r,{notice_id:s.notices[0].notice_id,kind:'handoff',decided_by:'root',decision_pointer:'WORK.md#handoff'});c.requestClaim(r,{ticket_id:b.ticket_id,lease_expires_at:lease()});c.ready(r,{ticket_id:b.ticket_id});c.freezeContour(r,{ticket_id:a.ticket_id});expect(c.status(r).contours[0].work_ids).toEqual(['first','second']);});
 test('unrelated files can both claim while shared BR/SR links their contour',()=>{const r=root();enqueue(r,'a','src/a.js');enqueue(r,'b','src/b.js');let s=c.status(r),a=s.tickets.find(x=>x.work_id==='a'),b=s.tickets.find(x=>x.work_id==='b');c.requestClaim(r,{ticket_id:a.ticket_id,lease_expires_at:lease()});c.requestClaim(r,{ticket_id:b.ticket_id,lease_expires_at:lease()});expect(c.validateClaim(r,{ticket_id:a.ticket_id}).claims[0].status).toBe('active');expect(c.validateClaim(r,{ticket_id:b.ticket_id}).claims[0].status).toBe('active');});
 test('one work can mutate claimed B while A waits, but cannot finalize until A is handed off',()=>{const r=root();enqueue(r,'owner','src/a.js');c.enqueue(r,{work_id:'mixed',thread_id:'thread-mixed',source_revision:'live-v1',contour_keys:['br:BR-1','file:src/a.js','file:src/b.js'],exclusive_resources:['file:src/a.js','file:src/b.js']});let s=c.status(r),owner=s.tickets.find(x=>x.work_id==='owner'),mixed=s.tickets.find(x=>x.work_id==='mixed');c.requestClaim(r,{ticket_id:owner.ticket_id,lease_expires_at:lease()});c.requestClaim(r,{ticket_id:mixed.ticket_id,resources:['file:src/b.js'],lease_expires_at:lease()});expect(c.validateClaim(r,{ticket_id:mixed.ticket_id,resources:['file:src/b.js']}).claims[0].resources).toEqual(['file:src/b.js']);expect(()=>c.validateClaim(r,{ticket_id:mixed.ticket_id,resources:['file:src/a.js']})).toThrow(/claim invalid/);expect(()=>c.ready(r,{ticket_id:mixed.ticket_id})).toThrow(/every scoped resource/);c.ready(r,{ticket_id:owner.ticket_id});const notice=c.status(r).notices.find(x=>x.contender_work_id==='mixed');c.disposition(r,{notice_id:notice.notice_id,kind:'handoff',decided_by:'root',decision_pointer:'WORK.md#handoff'});c.requestClaim(r,{ticket_id:mixed.ticket_id,resources:['file:src/a.js'],lease_expires_at:lease()});c.ready(r,{ticket_id:mixed.ticket_id});expect(c.status(r).tickets.find(x=>x.work_id==='mixed').status).toBe('ready_for_handoff');});
 test('expiry, malformed scope and invalid disposition fail closed',()=>{const r=root();expect(()=>c.enqueue(r,{...scope('bad','../bad.js')})).toThrow(/file invalid/);enqueue(r,'one','src/a.js');enqueue(r,'two','src/a.js');let s=c.status(r),one=s.tickets.find(x=>x.work_id==='one'),two=s.tickets.find(x=>x.work_id==='two');c.requestClaim(r,{ticket_id:one.ticket_id,lease_expires_at:lease()});expect(()=>c.disposition(r,{notice_id:s.notices[0].notice_id,kind:'unknown',decided_by:'root',decision_pointer:'WORK.md#handoff'})).toThrow(/invalid/);expect(()=>c.renewClaim(r,{ticket_id:one.ticket_id,lease_expires_at:'2000-01-01T00:00:00Z'})).toThrow(/expired/);expect(two.ticket_id).toBeTruthy();});
 test('ready contour produces one mixed-operation user-test batch and acceptance releases members',()=>{const r=root();enqueue(r,'a','src/a.js');enqueue(r,'b','src/b.js');let s=c.status(r);for(const t of s.tickets){c.requestClaim(r,{ticket_id:t.ticket_id,lease_expires_at:lease()});c.ready(r,{ticket_id:t.ticket_id});}c.freezeContour(r,{ticket_id:s.tickets[0].ticket_id});const contour=c.status(r).contours[0];expect(()=>c.buildBatch(r,{contour_id:contour.contour_id,operations:[{order:1,source:'src/a.js',destination:'Package A',operation:'import'}]})).toThrow(/assurance/);c.recordContourAssurance(r,{contour_id:contour.contour_id,integration_work_id:'integration-1',test_receipts:['tests/full'],review_receipt_ids:['r1','r2','r3'],reverse_receipt_ids:['v1','v2','v3']});c.buildBatch(r,{contour_id:contour.contour_id,operations:[{order:2,source:'src/b.js',destination:'Package B',operation:'copy'},{order:1,source:'src/a.js',destination:'Package A',operation:'import'}],do_not_deploy:['tests/a.test.cjs'],post_deployment_checks:[{id:'run',step:'Open feature',expected:'works'}]});const batch=c.status(r).batches[0];expect(batch.operations.map(x=>x.operation)).toEqual(['import','copy']);c.recordBatchDecision(r,{batch_id:batch.batch_id,decision:'accepted',decision_pointer:'WORK.md#user-accepted'});expect(c.status(r).tickets.every(x=>x.status==='released')).toBe(true);});
 test('combined contour assurance rejects incomplete or duplicate independent receipts',()=>{const r=root();enqueue(r,'a','src/a.js');let t=c.status(r).tickets[0];c.requestClaim(r,{ticket_id:t.ticket_id,lease_expires_at:lease()});c.ready(r,{ticket_id:t.ticket_id});c.freezeContour(r,{ticket_id:t.ticket_id});const contour=c.status(r).contours[0],base={contour_id:contour.contour_id,integration_work_id:'integration-1',test_receipts:['tests/full'],review_receipt_ids:['r1','r2','r3'],reverse_receipt_ids:['v1','v2','v3']};expect(()=>c.recordContourAssurance(r,{...base,review_receipt_ids:['r1','r1','r2']})).toThrow(/assurance/);expect(()=>c.recordContourAssurance(r,{...base,reverse_receipt_ids:['v1','v2']})).toThrow(/assurance/);});
});
