'use strict';
const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');
const { importLegacy } = require('../../agent-runtime/lib/legacy-import.cjs');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'legacy-import-'));
fs.writeFileSync(path.join(root, 'ready.json'), JSON.stringify({ id: 'run-1', status: 'ready_for_decision', fingerprint: 'f1', evidence: [{ class: 'Static', path: 'tests/x' }], leases: ['lease-1'], gaps: ['GAP-1'] }));
const receipt = importLegacy(root);
assert.equal(receipt.mode, 'read_only');
assert.equal(receipt.assertions.ready_for_decision_is_not_human_approval, true);
assert.equal(receipt.assertions.static_is_not_runtime, true);
assert.equal(receipt.records.length, 1);
assert.equal(receipt.records[0].approval.status, 'pending_human_decision');
assert.equal(receipt.records[0].approval.historical, true);
assert.equal(receipt.records[0].evidence[0].class, 'Static');
assert.notEqual(receipt.records[0].runtime.status, 'accepted');
const cliReceipt = JSON.parse(execFileSync(process.execPath, [path.join(__dirname, '../../agent-runtime/bin/legacy-import.cjs'), root], { encoding: 'utf8' }));
assert.equal(cliReceipt.schema, 'LegacyImportReceipt/v1');
assert.equal(cliReceipt.mode, 'read_only');
fs.rmSync(root, { recursive: true, force: true });
console.log('legacy import contract: pass');
