'use strict';
const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path');
const {execFileSync}=require('child_process'); const r=require('../../agent-runtime/lib/runtime.cjs');
const blocked=(f,n)=>assert.throws(f,/** @param {any} e */ e=>e&&e.code==='GATE_BLOCKED',n);
const root=fs.mkdtempSync(path.join(os.tmpdir(),'runtime-adversarial-'));execFileSync('git',['init','-q'],{cwd:root});execFileSync('git',['config','user.email','runtime@test'],{cwd:root});execFileSync('git',['config','user.name','runtime'],{cwd:root});fs.writeFileSync(path.join(root,'a'),'x');execFileSync('git',['add','.'],{cwd:root});execFileSync('git',['commit','-qm','runtime'],{cwd:root});
const scope={fingerprint_paths:['a'],absence_assertions:{gone:true}};assert.match(r.implementationFingerprint(scope,root),/^[a-f0-9]{64}$/);
const tooling=path.join(root,'tooling');fs.mkdirSync(path.join(tooling,'node_modules','dependency'),{recursive:true});fs.mkdirSync(path.join(tooling,'coverage'),{recursive:true});fs.mkdirSync(path.join(tooling,'.vitest'),{recursive:true});fs.writeFileSync(path.join(tooling,'package-lock.json'),'lock-v1');fs.writeFileSync(path.join(tooling,'node_modules','dependency','index.js'),'generated-v1');fs.writeFileSync(path.join(tooling,'coverage','summary.json'),'coverage-v1');fs.writeFileSync(path.join(tooling,'.vitest','cache'),'cache-v1');const toolingScope={fingerprint_paths:['tooling/**']};const toolingBefore=r.implementationFingerprint(toolingScope,root);fs.writeFileSync(path.join(tooling,'node_modules','dependency','index.js'),'generated-v2');fs.writeFileSync(path.join(tooling,'coverage','summary.json'),'coverage-v2');fs.writeFileSync(path.join(tooling,'.vitest','cache'),'cache-v2');assert.strictEqual(r.implementationFingerprint(toolingScope,root),toolingBefore,'derived tooling contents are excluded');fs.writeFileSync(path.join(tooling,'package-lock.json'),'lock-v2');assert.notStrictEqual(r.implementationFingerprint(toolingScope,root),toolingBefore,'lockfile remains sealed');fs.rmSync(path.join(tooling,'node_modules'),{recursive:true,force:true});fs.symlinkSync(path.join(tooling,'coverage'),path.join(tooling,'node_modules'),/** @type {'junction'} */ ('junction'));blocked(()=>r.implementationFingerprint(toolingScope,root),'derived directory reparse blocks');fs.rmdirSync(path.join(tooling,'node_modules'));
fs.mkdirSync(path.join(root,'dir'));fs.symlinkSync(path.join(root,'dir'),path.join(root,'gone'),/** @type {'junction'} */ ('junction'));blocked(()=>r.implementationFingerprint(scope,root),'junction absence counts present');fs.rmdirSync(path.join(root,'gone'));
fs.symlinkSync(path.join(root,'dir'),path.join(root,'linkdir'),/** @type {'junction'} */ ('junction'));blocked(()=>r.resolveScope({fingerprint_paths:['linkdir/**']},root),'scope reparse blocks');
const outside=path.join(root,'outside.json');fs.writeFileSync(outside,'{}');blocked(()=>r.validateGateFile({checkpointPath:outside,expectedRevision:1,sourceRevision:'x',repoRoot:root,point:'plan:pre'}),'checkpoint outside work root');
const schemas=['evidence.v1.schema.json','runtime-receipt.v2.schema.json','reverse-validation-receipt.v1.schema.json','recovery-evidence.v1.schema.json','import-attribution.v1.schema.json'];for(const name of schemas){const s=JSON.parse(fs.readFileSync(path.join(__dirname,'../../agent-runtime/schemas',name),'utf8'));assert.strictEqual(s.additionalProperties,false);for(const key of ['work_id','source_revision','sealed_revision','implementation_fingerprint','acceptance_manifest_id','acceptance_manifest_version'])assert.ok(s.required.includes(key));}
const early='2026-01-01T10:00:00+03:00',late='2026-01-01T07:30:00Z';assert.ok(Date.parse(late)>Date.parse(early),'timezone comparison uses instant');
console.log('runtime adversarial contract: pass');
