const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path');
const {execFileSync}=require('child_process'); const r=require('../../agent-runtime/lib/runtime.cjs');
function blocked(f,n){assert.throws(f,/** @param {any} e */ e=>e&&e.code==='GATE_BLOCKED',n);}
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'runtime-contract-'));execFileSync('git',['init','-q'],{cwd:tmp});execFileSync('git',['config','user.email','runtime@test'],{cwd:tmp});execFileSync('git',['config','user.name','runtime'],{cwd:tmp});fs.writeFileSync(path.join(tmp,'a.txt'),'one');execFileSync('git',['add','.'],{cwd:tmp});execFileSync('git',['commit','-qm','base'],{cwd:tmp});
const work=path.join(tmp,'.agent','work','contract');fs.mkdirSync(work,{recursive:true});const file=path.join(work,'resume.json'),source='runtime-contract';
const plan={br:'intent',sr:'behavior',ac:'acceptance',gaps:['GAP-RUNTIME'],scope:'a.txt',verification:'test',rollback_cleanup:'revert'};
const mf={schema:'AcceptanceManifest/v1',id:'AC-RUNTIME',version:1,ac_ids:['AC-1','AC-2'],contracts:[{id:'AC-1',definition:'contract',sr:'SR-1',evidence:['Static']} ,{id:'AC-2',definition:'contract',sr:'SR-2',evidence:['GAP']}],source:'manifest.json',scope:'a.txt',source_revision:source};
const base={schema:'WorkCheckpoint/v2',work_id:'contract',revision:1,lifecycle_state:'INTAKE',protocol_version:'agent-development-runtime/v2',route:'R3',risk:'high',change_kind:'migration',source_revision:source,allowed_paths:['a.txt'],fingerprint_paths:['a.txt'],absence_assertions:{gone:true},source_plan:plan,acceptance:['AC-1'],test_plan:['test'],acceptance_manifest:mf,reviews:[],verification:[],evidence:[],recovery_evidence:[],leases:[],imports:[],review_generation:0,review_generation_ledger:[],question_candidates:[],next_action:'trace'};fs.writeFileSync(file,JSON.stringify(base));
blocked(()=>r.validateGate(base,'plan:pre',{expectedRevision:1,sourceRevision:source,root:tmp}),'INTAKE cannot plan'); const unknown={...base,risk:'critical'};blocked(()=>r.validateGate(unknown,'plan:pre',{expectedRevision:1,sourceRevision:source,root:tmp}),'critical never bypasses gate');
let c=r.beginTrace(file,{expectedRevision:1,sourceRevision:source});c=r.replanWork(file,{expectedRevision:c.revision,sourceRevision:source,sourcePlan:plan,acceptance:['AC-1'],testPlan:['test'],acceptanceManifest:mf});c=r.beginExecution(file,{expectedRevision:c.revision,sourceRevision:source,approval:{source_revision:source,pointer:'WORK.md#approval'}});c=r.sealMutation(file,c.revision,source,tmp);const fp=c.implementation_fingerprint;
const bind={work_id:'contract',source_revision:source,sealed_revision:c.sealed_revision,implementation_fingerprint:fp,acceptance_manifest_id:'AC-RUNTIME',acceptance_manifest_version:1};
const packet={schema:'BlindReviewPacket/v2',packet_id:'runtime-review',packet_version:1,wave:1,generation:1,work_id:'contract',source_revision:source,sealed_revision:c.sealed_revision,implementation_fingerprint:fp,acceptance_manifest_id:'AC-RUNTIME',acceptance_manifest_version:1,status:'frozen',required_profile:{model:'configured',reasoning:'high'},review_scope:{paths:['a.txt'],absence_assertions:{gone:true}},profile_attestation_set:'dispatch.json'};c=r.freezeReviewPacket(file,packet,c.revision,source);
const set={schema:'DispatchProfileAttestationSet/v1',...bind,packet_id:'runtime-review',packet_version:1,wave:1,orchestrator:'root',selector_source:'trusted',requested_model:'configured',requested_reasoning_effort:'high',runtime_metadata_observed:false,issued_at:new Date().toISOString(),root_task_id:'root-task',root_dispatch_id:'root-dispatch',entries:r.lenses.map((lens,i)=>({task_id:`t${i}`,dispatch_id:`d${i}`,reviewer_id:`r${i}`,lens,profile_verified:true,profile_verification:{verified_model:'configured',verified_reasoning_effort:'high',verification_source:'runtime/profile-verifier',verification_pointer:`tests/runtime-profile-${i}`,verified_at:new Date().toISOString()}}))};c=r.recordDispatchAttestationSet(file,set,c.revision,source,tmp);
for(let i=0;i<3;i++)c=r.recordReviewReceipt(file,{schema:'ReviewReceipt/v2',...bind,reviewer_id:`r${i}`,dispatch_task_id:`t${i}`,dispatch_id:`d${i}`,lens:r.lenses[i],wave:1,packet_id:'runtime-review',packet_version:1,history_isolation:true,findings:[],verdict:'clean'},c.revision,source,tmp);
blocked(()=>r.recordReviewReceipt(file,{schema:'ReviewReceipt/v2',...bind,reviewer_id:'r0',dispatch_task_id:'t0',dispatch_id:'d0',lens:r.lenses[0],wave:1,packet_id:'runtime-review',packet_version:1,history_isolation:true,findings:[],verdict:'clean'},c.revision,source,tmp),'duplicate reviewer');
for(const [i,type] of ['trace_scope','technical_safety','evidence_truth'].entries())c=r.recordReverseValidationReceipt(file,{schema:'ReverseValidationReceipt/v1',...bind,receipt_id:`rv${i}`,reviewer_id:`v${i}`,type,verdict:'pass',validator:'independent',timestamp:new Date().toISOString(),evidence:['test'],ac_refs:['AC-1'],packet_id:'runtime-review',packet_version:1},c.revision,source,tmp);
c=r.recordRecoveryEvidence(file,{schema:'RecoveryEvidence/v1',...bind,id:'recovery',action:'rollback drill',actor:'tester',attribution:'tests/runtime',result:'pass',rollback:'revert',timestamp:new Date().toISOString(),ac_refs:['AC-1']},c.revision,source);blocked(()=>r.recordRecoveryEvidence(file,{schema:'RecoveryEvidence/v1',...bind,id:'recovery',action:'rollback drill',actor:'tester',attribution:'tests/runtime',result:'pass',rollback:'revert',timestamp:new Date().toISOString(),ac_refs:['AC-1']},c.revision,source),'duplicate recovery');
c=r.recordEvidence(file,{schema:'Evidence/v1',...bind,id:'static',class:'Static',pointer:'tests/runtime',timestamp:new Date().toISOString(),ac_refs:['AC-1']},c.revision,source);blocked(()=>r.recordEvidence(file,{schema:'Evidence/v1',...bind,id:'static',class:'Static',pointer:'tests/runtime',timestamp:new Date().toISOString(),ac_refs:['AC-1']},c.revision,source),'duplicate evidence');
blocked(()=>r.recordImportAttribution(file,{schema:'ImportAttribution/v1',...bind,import_id:'old',provider:'p',receipt_pointer:'x',imported_at:'2000-01-01T00:00:00Z',status:'accepted'},c.revision,source),'stale import');
c=r.recordImportAttribution(file,{schema:'ImportAttribution/v1',...bind,import_id:'ok',provider:'p',receipt_pointer:'import.json',imported_at:new Date().toISOString(),status:'accepted'},c.revision,source);blocked(()=>r.recordImportAttribution(file,{schema:'ImportAttribution/v1',...bind,import_id:'ok',provider:'p',receipt_pointer:'import.json',imported_at:new Date().toISOString(),status:'accepted'},c.revision,source),'duplicate import');
c=r.advanceToDelivery(file,{expectedRevision:c.revision,sourceRevision:source,root:tmp});
const deployment={schema:'DeploymentManifest/v1',...bind,delivery_cycle_id:c.delivery_cycle_id,created:[],modified:['a.txt'],deploy:[{source:'a.txt',destination:'Target Platform package',operation:'import',order:1}],do_not_deploy:[],post_deployment_checks:[{id:'check-runtime',step:'Run the runtime acceptance check.',expected:'The acceptance check passes.',ac_refs:['AC-1']}]};const delivery={schema:'DeliveryReceipt/v2',...bind,delivery_cycle_id:c.delivery_cycle_id,decision:'approved',actor:'user',source:'chat',timestamp:new Date().toISOString(),sanitized_pointers:['WORK.md#delivery'],deployment_manifest:deployment};c=r.recordDeliveryReceipt(file,delivery,c.revision,source);
blocked(()=>r.recordRuntimeReceipt(file,{schema:'RuntimeReceipt/v2',...bind,status:'accepted',blocking:false,environment:'dev',actor:'user',timestamp:'2000-01-01T00:00:00Z',ac_refs:['AC-1'],sanitized_pointers:['runtime']},c.revision,source),'stale runtime');
const rt={schema:'RuntimeReceipt/v2',...bind,status:'accepted',blocking:false,environment:'local',actor:'user',timestamp:new Date().toISOString(),ac_refs:['AC-1'],sanitized_pointers:['runtime/evidence']};c=r.recordRuntimeReceipt(file,rt,c.revision,source);c=r.completeWork(file,{expectedRevision:c.revision,sourceRevision:source,root:tmp});assert.equal(c.lifecycle_state,'COMPLETE');assert.doesNotThrow(()=>r.validateGateFile({checkpointPath:file,expectedRevision:c.revision,sourceRevision:source,repoRoot:tmp,point:'ship:post'}));
blocked(()=>r.recordEvidence(file,{schema:'Evidence/v1',...bind,id:'after',class:'Static',pointer:'x',timestamp:new Date().toISOString(),ac_refs:['AC-1']},c.revision,source),'complete immutable');
const c2=JSON.parse(fs.readFileSync(file,'utf8'));c2.runtime_receipt.blocking=true;fs.writeFileSync(file,JSON.stringify(c2));blocked(()=>r.validateGateFile({checkpointPath:file,expectedRevision:c.revision,sourceRevision:source,repoRoot:tmp,point:'ship:post'}),'blocking runtime needs Runtime evidence');c2.runtime_receipt.blocking=false;c2.reviews[0].reviewer_id='tampered';fs.writeFileSync(file,JSON.stringify(c2));blocked(()=>r.validateGateFile({checkpointPath:file,expectedRevision:c.revision,sourceRevision:source,repoRoot:tmp,point:'ship:post'}),'tampered checkpoint');
console.log('runtime contract: pass');

